/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsIndexRouteImport } from './routes/docs/index'
import { Route as landingTermsOfServiceRouteImport } from './routes/(landing)/terms-of-service'
import { Route as landingPrivacyPolicyRouteImport } from './routes/(landing)/privacy-policy'
import { Route as landingPricingRouteImport } from './routes/(landing)/pricing'
import { Route as landingHomeRouteImport } from './routes/(landing)/home'
import { Route as landingContactRouteImport } from './routes/(landing)/contact'
import { Route as landingAboutRouteImport } from './routes/(landing)/about'
import { Route as authUnauthorizedRouteImport } from './routes/(auth)/unauthorized'
import { Route as authSignupRouteImport } from './routes/(auth)/signup'
import { Route as authSigninRouteImport } from './routes/(auth)/signin'
import { Route as authResetPasswordRouteImport } from './routes/(auth)/reset-password'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as dashboardSupportSupportRouteImport } from './routes/(dashboard)/support/support'
import { Route as dashboardSupportStatementsRouteImport } from './routes/(dashboard)/support/statements'
import { Route as dashboardSupportSettingsRouteImport } from './routes/(dashboard)/support/settings'
import { Route as dashboardSupportPaymentsRouteImport } from './routes/(dashboard)/support/payments'
import { Route as dashboardSupportOverviewRouteImport } from './routes/(dashboard)/support/overview'
import { Route as dashboardSuperadminSettingsRouteImport } from './routes/(dashboard)/superadmin/settings'
import { Route as dashboardSuperadminReportsRouteImport } from './routes/(dashboard)/superadmin/reports'
import { Route as dashboardSuperadminEmployeesRouteImport } from './routes/(dashboard)/superadmin/employees'
import { Route as dashboardSuperadminBranchesRouteImport } from './routes/(dashboard)/superadmin/branches'
import { Route as dashboardStaffSupportRouteImport } from './routes/(dashboard)/staff/support'
import { Route as dashboardStaffStatementsRouteImport } from './routes/(dashboard)/staff/statements'
import { Route as dashboardStaffSettingsRouteImport } from './routes/(dashboard)/staff/settings'
import { Route as dashboardStaffPaymentsRouteImport } from './routes/(dashboard)/staff/payments'
import { Route as dashboardStaffOverviewRouteImport } from './routes/(dashboard)/staff/overview'
import { Route as dashboardOwnerStaffPerformanceRouteImport } from './routes/(dashboard)/owner/staff-performance'
import { Route as dashboardOwnerSettingsRouteImport } from './routes/(dashboard)/owner/settings'
import { Route as dashboardOwnerReportsRouteImport } from './routes/(dashboard)/owner/reports'
import { Route as dashboardOwnerBranchesRouteImport } from './routes/(dashboard)/owner/branches'
import { Route as dashboardManagerSupportRouteImport } from './routes/(dashboard)/manager/support'
import { Route as dashboardManagerStatementsRouteImport } from './routes/(dashboard)/manager/statements'
import { Route as dashboardManagerSettingsRouteImport } from './routes/(dashboard)/manager/settings'
import { Route as dashboardManagerPaymentsRouteImport } from './routes/(dashboard)/manager/payments'
import { Route as dashboardManagerOverviewRouteImport } from './routes/(dashboard)/manager/overview'
import { Route as dashboardDashboardTransactionsRouteImport } from './routes/(dashboard)/dashboard/transactions'
import { Route as dashboardDashboardSupportRouteImport } from './routes/(dashboard)/dashboard/support'
import { Route as dashboardDashboardStatementsRouteImport } from './routes/(dashboard)/dashboard/statements'
import { Route as dashboardDashboardSettingsRouteImport } from './routes/(dashboard)/dashboard/settings'
import { Route as dashboardDashboardPaymentsRouteImport } from './routes/(dashboard)/dashboard/payments'
import { Route as dashboardDashboardOverviewRouteImport } from './routes/(dashboard)/dashboard/overview'
import { Route as dashboardDashboardCardsRouteImport } from './routes/(dashboard)/dashboard/cards'
import { Route as dashboardAuditSupportRouteImport } from './routes/(dashboard)/audit/support'
import { Route as dashboardAuditStatementsRouteImport } from './routes/(dashboard)/audit/statements'
import { Route as dashboardAuditSettingsRouteImport } from './routes/(dashboard)/audit/settings'
import { Route as dashboardAuditPaymentsRouteImport } from './routes/(dashboard)/audit/payments'
import { Route as dashboardAuditOverviewRouteImport } from './routes/(dashboard)/audit/overview'
import { Route as dashboardAdminSupportRouteImport } from './routes/(dashboard)/admin/support'
import { Route as dashboardAdminFlaggedRouteImport } from './routes/(dashboard)/admin/flagged'
import { Route as dashboardAdminComplianceRouteImport } from './routes/(dashboard)/admin/compliance'
import { Route as dashboardAdminAuditTrailsRouteImport } from './routes/(dashboard)/admin/audit-trails'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/docs/',
  path: '/docs/',
  getParentRoute: () => rootRouteImport,
} as any)
const landingTermsOfServiceRoute = landingTermsOfServiceRouteImport.update({
  id: '/(landing)/terms-of-service',
  path: '/terms-of-service',
  getParentRoute: () => rootRouteImport,
} as any)
const landingPrivacyPolicyRoute = landingPrivacyPolicyRouteImport.update({
  id: '/(landing)/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const landingPricingRoute = landingPricingRouteImport.update({
  id: '/(landing)/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const landingHomeRoute = landingHomeRouteImport.update({
  id: '/(landing)/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const landingContactRoute = landingContactRouteImport.update({
  id: '/(landing)/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const landingAboutRoute = landingAboutRouteImport.update({
  id: '/(landing)/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const authUnauthorizedRoute = authUnauthorizedRouteImport.update({
  id: '/(auth)/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignupRoute = authSignupRouteImport.update({
  id: '/(auth)/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const authSigninRoute = authSigninRouteImport.update({
  id: '/(auth)/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const authResetPasswordRoute = authResetPasswordRouteImport.update({
  id: '/(auth)/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboardSupportSupportRoute = dashboardSupportSupportRouteImport.update({
  id: '/(dashboard)/support/support',
  path: '/support/support',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboardSupportStatementsRoute =
  dashboardSupportStatementsRouteImport.update({
    id: '/(dashboard)/support/statements',
    path: '/support/statements',
    getParentRoute: () => rootRouteImport,
  } as any)
const dashboardSupportSettingsRoute =
  dashboardSupportSettingsRouteImport.update({
    id: '/(dashboard)/support/settings',
    path: '/support/settings',
    getParentRoute: () => rootRouteImport,
  } as any)
const dashboardSupportPaymentsRoute =
  dashboardSupportPaymentsRouteImport.update({
    id: '/(dashboard)/support/payments',
    path: '/support/payments',
    getParentRoute: () => rootRouteImport,
  } as any)
const dashboardSupportOverviewRoute =
  dashboardSupportOverviewRouteImport.update({
    id: '/(dashboard)/support/overview',
    path: '/support/overview',
    getParentRoute: () => rootRouteImport,
  } as any)
const dashboardSuperadminSettingsRoute =
  dashboardSuperadminSettingsRouteImport.update({
    id: '/(dashboard)/superadmin/settings',
    path: '/superadmin/settings',
    getParentRoute: () => rootRouteImport,
  } as any)
const dashboardSuperadminReportsRoute =
  dashboardSuperadminReportsRouteImport.update({
    id: '/(dashboard)/superadmin/reports',
    path: '/superadmin/reports',
    getParentRoute: () => rootRouteImport,
  } as any)
const dashboardSuperadminEmployeesRoute =
  dashboardSuperadminEmployeesRouteImport.update({
    id: '/(dashboard)/superadmin/employees',
    path: '/superadmin/employees',
    getParentRoute: () => rootRouteImport,
  } as any)
const dashboardSuperadminBranchesRoute =
  dashboardSuperadminBranchesRouteImport.update({
    id: '/(dashboard)/superadmin/branches',
    path: '/superadmin/branches',
    getParentRoute: () => rootRouteImport,
  } as any)
const dashboardStaffSupportRoute = dashboardStaffSupportRouteImport.update({
  id: '/(dashboard)/staff/support',
  path: '/staff/support',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboardStaffStatementsRoute =
  dashboardStaffStatementsRouteImport.update({
    id: '/(dashboard)/staff/statements',
    path: '/staff/statements',
    getParentRoute: () => rootRouteImport,
  } as any)
const dashboardStaffSettingsRoute = dashboardStaffSettingsRouteImport.update({
  id: '/(dashboard)/staff/settings',
  path: '/staff/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboardStaffPaymentsRoute = dashboardStaffPaymentsRouteImport.update({
  id: '/(dashboard)/staff/payments',
  path: '/staff/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboardStaffOverviewRoute = dashboardStaffOverviewRouteImport.update({
  id: '/(dashboard)/staff/overview',
  path: '/staff/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboardOwnerStaffPerformanceRoute =
  dashboardOwnerStaffPerformanceRouteImport.update({
    id: '/(dashboard)/owner/staff-performance',
    path: '/owner/staff-performance',
    getParentRoute: () => rootRouteImport,
  } as any)
const dashboardOwnerSettingsRoute = dashboardOwnerSettingsRouteImport.update({
  id: '/(dashboard)/owner/settings',
  path: '/owner/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboardOwnerReportsRoute = dashboardOwnerReportsRouteImport.update({
  id: '/(dashboard)/owner/reports',
  path: '/owner/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboardOwnerBranchesRoute = dashboardOwnerBranchesRouteImport.update({
  id: '/(dashboard)/owner/branches',
  path: '/owner/branches',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboardManagerSupportRoute = dashboardManagerSupportRouteImport.update({
  id: '/(dashboard)/manager/support',
  path: '/manager/support',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboardManagerStatementsRoute =
  dashboardManagerStatementsRouteImport.update({
    id: '/(dashboard)/manager/statements',
    path: '/manager/statements',
    getParentRoute: () => rootRouteImport,
  } as any)
const dashboardManagerSettingsRoute =
  dashboardManagerSettingsRouteImport.update({
    id: '/(dashboard)/manager/settings',
    path: '/manager/settings',
    getParentRoute: () => rootRouteImport,
  } as any)
const dashboardManagerPaymentsRoute =
  dashboardManagerPaymentsRouteImport.update({
    id: '/(dashboard)/manager/payments',
    path: '/manager/payments',
    getParentRoute: () => rootRouteImport,
  } as any)
const dashboardManagerOverviewRoute =
  dashboardManagerOverviewRouteImport.update({
    id: '/(dashboard)/manager/overview',
    path: '/manager/overview',
    getParentRoute: () => rootRouteImport,
  } as any)
const dashboardDashboardTransactionsRoute =
  dashboardDashboardTransactionsRouteImport.update({
    id: '/(dashboard)/dashboard/transactions',
    path: '/dashboard/transactions',
    getParentRoute: () => rootRouteImport,
  } as any)
const dashboardDashboardSupportRoute =
  dashboardDashboardSupportRouteImport.update({
    id: '/(dashboard)/dashboard/support',
    path: '/dashboard/support',
    getParentRoute: () => rootRouteImport,
  } as any)
const dashboardDashboardStatementsRoute =
  dashboardDashboardStatementsRouteImport.update({
    id: '/(dashboard)/dashboard/statements',
    path: '/dashboard/statements',
    getParentRoute: () => rootRouteImport,
  } as any)
const dashboardDashboardSettingsRoute =
  dashboardDashboardSettingsRouteImport.update({
    id: '/(dashboard)/dashboard/settings',
    path: '/dashboard/settings',
    getParentRoute: () => rootRouteImport,
  } as any)
const dashboardDashboardPaymentsRoute =
  dashboardDashboardPaymentsRouteImport.update({
    id: '/(dashboard)/dashboard/payments',
    path: '/dashboard/payments',
    getParentRoute: () => rootRouteImport,
  } as any)
const dashboardDashboardOverviewRoute =
  dashboardDashboardOverviewRouteImport.update({
    id: '/(dashboard)/dashboard/overview',
    path: '/dashboard/overview',
    getParentRoute: () => rootRouteImport,
  } as any)
const dashboardDashboardCardsRoute = dashboardDashboardCardsRouteImport.update({
  id: '/(dashboard)/dashboard/cards',
  path: '/dashboard/cards',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboardAuditSupportRoute = dashboardAuditSupportRouteImport.update({
  id: '/(dashboard)/audit/support',
  path: '/audit/support',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboardAuditStatementsRoute =
  dashboardAuditStatementsRouteImport.update({
    id: '/(dashboard)/audit/statements',
    path: '/audit/statements',
    getParentRoute: () => rootRouteImport,
  } as any)
const dashboardAuditSettingsRoute = dashboardAuditSettingsRouteImport.update({
  id: '/(dashboard)/audit/settings',
  path: '/audit/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboardAuditPaymentsRoute = dashboardAuditPaymentsRouteImport.update({
  id: '/(dashboard)/audit/payments',
  path: '/audit/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboardAuditOverviewRoute = dashboardAuditOverviewRouteImport.update({
  id: '/(dashboard)/audit/overview',
  path: '/audit/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboardAdminSupportRoute = dashboardAdminSupportRouteImport.update({
  id: '/(dashboard)/admin/support',
  path: '/admin/support',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboardAdminFlaggedRoute = dashboardAdminFlaggedRouteImport.update({
  id: '/(dashboard)/admin/flagged',
  path: '/admin/flagged',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboardAdminComplianceRoute =
  dashboardAdminComplianceRouteImport.update({
    id: '/(dashboard)/admin/compliance',
    path: '/admin/compliance',
    getParentRoute: () => rootRouteImport,
  } as any)
const dashboardAdminAuditTrailsRoute =
  dashboardAdminAuditTrailsRouteImport.update({
    id: '/(dashboard)/admin/audit-trails',
    path: '/admin/audit-trails',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/reset-password': typeof authResetPasswordRoute
  '/signin': typeof authSigninRoute
  '/signup': typeof authSignupRoute
  '/unauthorized': typeof authUnauthorizedRoute
  '/about': typeof landingAboutRoute
  '/contact': typeof landingContactRoute
  '/home': typeof landingHomeRoute
  '/pricing': typeof landingPricingRoute
  '/privacy-policy': typeof landingPrivacyPolicyRoute
  '/terms-of-service': typeof landingTermsOfServiceRoute
  '/docs': typeof DocsIndexRoute
  '/admin/audit-trails': typeof dashboardAdminAuditTrailsRoute
  '/admin/compliance': typeof dashboardAdminComplianceRoute
  '/admin/flagged': typeof dashboardAdminFlaggedRoute
  '/admin/support': typeof dashboardAdminSupportRoute
  '/audit/overview': typeof dashboardAuditOverviewRoute
  '/audit/payments': typeof dashboardAuditPaymentsRoute
  '/audit/settings': typeof dashboardAuditSettingsRoute
  '/audit/statements': typeof dashboardAuditStatementsRoute
  '/audit/support': typeof dashboardAuditSupportRoute
  '/dashboard/cards': typeof dashboardDashboardCardsRoute
  '/dashboard/overview': typeof dashboardDashboardOverviewRoute
  '/dashboard/payments': typeof dashboardDashboardPaymentsRoute
  '/dashboard/settings': typeof dashboardDashboardSettingsRoute
  '/dashboard/statements': typeof dashboardDashboardStatementsRoute
  '/dashboard/support': typeof dashboardDashboardSupportRoute
  '/dashboard/transactions': typeof dashboardDashboardTransactionsRoute
  '/manager/overview': typeof dashboardManagerOverviewRoute
  '/manager/payments': typeof dashboardManagerPaymentsRoute
  '/manager/settings': typeof dashboardManagerSettingsRoute
  '/manager/statements': typeof dashboardManagerStatementsRoute
  '/manager/support': typeof dashboardManagerSupportRoute
  '/owner/branches': typeof dashboardOwnerBranchesRoute
  '/owner/reports': typeof dashboardOwnerReportsRoute
  '/owner/settings': typeof dashboardOwnerSettingsRoute
  '/owner/staff-performance': typeof dashboardOwnerStaffPerformanceRoute
  '/staff/overview': typeof dashboardStaffOverviewRoute
  '/staff/payments': typeof dashboardStaffPaymentsRoute
  '/staff/settings': typeof dashboardStaffSettingsRoute
  '/staff/statements': typeof dashboardStaffStatementsRoute
  '/staff/support': typeof dashboardStaffSupportRoute
  '/superadmin/branches': typeof dashboardSuperadminBranchesRoute
  '/superadmin/employees': typeof dashboardSuperadminEmployeesRoute
  '/superadmin/reports': typeof dashboardSuperadminReportsRoute
  '/superadmin/settings': typeof dashboardSuperadminSettingsRoute
  '/support/overview': typeof dashboardSupportOverviewRoute
  '/support/payments': typeof dashboardSupportPaymentsRoute
  '/support/settings': typeof dashboardSupportSettingsRoute
  '/support/statements': typeof dashboardSupportStatementsRoute
  '/support/support': typeof dashboardSupportSupportRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/reset-password': typeof authResetPasswordRoute
  '/signin': typeof authSigninRoute
  '/signup': typeof authSignupRoute
  '/unauthorized': typeof authUnauthorizedRoute
  '/about': typeof landingAboutRoute
  '/contact': typeof landingContactRoute
  '/home': typeof landingHomeRoute
  '/pricing': typeof landingPricingRoute
  '/privacy-policy': typeof landingPrivacyPolicyRoute
  '/terms-of-service': typeof landingTermsOfServiceRoute
  '/docs': typeof DocsIndexRoute
  '/admin/audit-trails': typeof dashboardAdminAuditTrailsRoute
  '/admin/compliance': typeof dashboardAdminComplianceRoute
  '/admin/flagged': typeof dashboardAdminFlaggedRoute
  '/admin/support': typeof dashboardAdminSupportRoute
  '/audit/overview': typeof dashboardAuditOverviewRoute
  '/audit/payments': typeof dashboardAuditPaymentsRoute
  '/audit/settings': typeof dashboardAuditSettingsRoute
  '/audit/statements': typeof dashboardAuditStatementsRoute
  '/audit/support': typeof dashboardAuditSupportRoute
  '/dashboard/cards': typeof dashboardDashboardCardsRoute
  '/dashboard/overview': typeof dashboardDashboardOverviewRoute
  '/dashboard/payments': typeof dashboardDashboardPaymentsRoute
  '/dashboard/settings': typeof dashboardDashboardSettingsRoute
  '/dashboard/statements': typeof dashboardDashboardStatementsRoute
  '/dashboard/support': typeof dashboardDashboardSupportRoute
  '/dashboard/transactions': typeof dashboardDashboardTransactionsRoute
  '/manager/overview': typeof dashboardManagerOverviewRoute
  '/manager/payments': typeof dashboardManagerPaymentsRoute
  '/manager/settings': typeof dashboardManagerSettingsRoute
  '/manager/statements': typeof dashboardManagerStatementsRoute
  '/manager/support': typeof dashboardManagerSupportRoute
  '/owner/branches': typeof dashboardOwnerBranchesRoute
  '/owner/reports': typeof dashboardOwnerReportsRoute
  '/owner/settings': typeof dashboardOwnerSettingsRoute
  '/owner/staff-performance': typeof dashboardOwnerStaffPerformanceRoute
  '/staff/overview': typeof dashboardStaffOverviewRoute
  '/staff/payments': typeof dashboardStaffPaymentsRoute
  '/staff/settings': typeof dashboardStaffSettingsRoute
  '/staff/statements': typeof dashboardStaffStatementsRoute
  '/staff/support': typeof dashboardStaffSupportRoute
  '/superadmin/branches': typeof dashboardSuperadminBranchesRoute
  '/superadmin/employees': typeof dashboardSuperadminEmployeesRoute
  '/superadmin/reports': typeof dashboardSuperadminReportsRoute
  '/superadmin/settings': typeof dashboardSuperadminSettingsRoute
  '/support/overview': typeof dashboardSupportOverviewRoute
  '/support/payments': typeof dashboardSupportPaymentsRoute
  '/support/settings': typeof dashboardSupportSettingsRoute
  '/support/statements': typeof dashboardSupportStatementsRoute
  '/support/support': typeof dashboardSupportSupportRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/reset-password': typeof authResetPasswordRoute
  '/(auth)/signin': typeof authSigninRoute
  '/(auth)/signup': typeof authSignupRoute
  '/(auth)/unauthorized': typeof authUnauthorizedRoute
  '/(landing)/about': typeof landingAboutRoute
  '/(landing)/contact': typeof landingContactRoute
  '/(landing)/home': typeof landingHomeRoute
  '/(landing)/pricing': typeof landingPricingRoute
  '/(landing)/privacy-policy': typeof landingPrivacyPolicyRoute
  '/(landing)/terms-of-service': typeof landingTermsOfServiceRoute
  '/docs/': typeof DocsIndexRoute
  '/(dashboard)/admin/audit-trails': typeof dashboardAdminAuditTrailsRoute
  '/(dashboard)/admin/compliance': typeof dashboardAdminComplianceRoute
  '/(dashboard)/admin/flagged': typeof dashboardAdminFlaggedRoute
  '/(dashboard)/admin/support': typeof dashboardAdminSupportRoute
  '/(dashboard)/audit/overview': typeof dashboardAuditOverviewRoute
  '/(dashboard)/audit/payments': typeof dashboardAuditPaymentsRoute
  '/(dashboard)/audit/settings': typeof dashboardAuditSettingsRoute
  '/(dashboard)/audit/statements': typeof dashboardAuditStatementsRoute
  '/(dashboard)/audit/support': typeof dashboardAuditSupportRoute
  '/(dashboard)/dashboard/cards': typeof dashboardDashboardCardsRoute
  '/(dashboard)/dashboard/overview': typeof dashboardDashboardOverviewRoute
  '/(dashboard)/dashboard/payments': typeof dashboardDashboardPaymentsRoute
  '/(dashboard)/dashboard/settings': typeof dashboardDashboardSettingsRoute
  '/(dashboard)/dashboard/statements': typeof dashboardDashboardStatementsRoute
  '/(dashboard)/dashboard/support': typeof dashboardDashboardSupportRoute
  '/(dashboard)/dashboard/transactions': typeof dashboardDashboardTransactionsRoute
  '/(dashboard)/manager/overview': typeof dashboardManagerOverviewRoute
  '/(dashboard)/manager/payments': typeof dashboardManagerPaymentsRoute
  '/(dashboard)/manager/settings': typeof dashboardManagerSettingsRoute
  '/(dashboard)/manager/statements': typeof dashboardManagerStatementsRoute
  '/(dashboard)/manager/support': typeof dashboardManagerSupportRoute
  '/(dashboard)/owner/branches': typeof dashboardOwnerBranchesRoute
  '/(dashboard)/owner/reports': typeof dashboardOwnerReportsRoute
  '/(dashboard)/owner/settings': typeof dashboardOwnerSettingsRoute
  '/(dashboard)/owner/staff-performance': typeof dashboardOwnerStaffPerformanceRoute
  '/(dashboard)/staff/overview': typeof dashboardStaffOverviewRoute
  '/(dashboard)/staff/payments': typeof dashboardStaffPaymentsRoute
  '/(dashboard)/staff/settings': typeof dashboardStaffSettingsRoute
  '/(dashboard)/staff/statements': typeof dashboardStaffStatementsRoute
  '/(dashboard)/staff/support': typeof dashboardStaffSupportRoute
  '/(dashboard)/superadmin/branches': typeof dashboardSuperadminBranchesRoute
  '/(dashboard)/superadmin/employees': typeof dashboardSuperadminEmployeesRoute
  '/(dashboard)/superadmin/reports': typeof dashboardSuperadminReportsRoute
  '/(dashboard)/superadmin/settings': typeof dashboardSuperadminSettingsRoute
  '/(dashboard)/support/overview': typeof dashboardSupportOverviewRoute
  '/(dashboard)/support/payments': typeof dashboardSupportPaymentsRoute
  '/(dashboard)/support/settings': typeof dashboardSupportSettingsRoute
  '/(dashboard)/support/statements': typeof dashboardSupportStatementsRoute
  '/(dashboard)/support/support': typeof dashboardSupportSupportRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/reset-password'
    | '/signin'
    | '/signup'
    | '/unauthorized'
    | '/about'
    | '/contact'
    | '/home'
    | '/pricing'
    | '/privacy-policy'
    | '/terms-of-service'
    | '/docs'
    | '/admin/audit-trails'
    | '/admin/compliance'
    | '/admin/flagged'
    | '/admin/support'
    | '/audit/overview'
    | '/audit/payments'
    | '/audit/settings'
    | '/audit/statements'
    | '/audit/support'
    | '/dashboard/cards'
    | '/dashboard/overview'
    | '/dashboard/payments'
    | '/dashboard/settings'
    | '/dashboard/statements'
    | '/dashboard/support'
    | '/dashboard/transactions'
    | '/manager/overview'
    | '/manager/payments'
    | '/manager/settings'
    | '/manager/statements'
    | '/manager/support'
    | '/owner/branches'
    | '/owner/reports'
    | '/owner/settings'
    | '/owner/staff-performance'
    | '/staff/overview'
    | '/staff/payments'
    | '/staff/settings'
    | '/staff/statements'
    | '/staff/support'
    | '/superadmin/branches'
    | '/superadmin/employees'
    | '/superadmin/reports'
    | '/superadmin/settings'
    | '/support/overview'
    | '/support/payments'
    | '/support/settings'
    | '/support/statements'
    | '/support/support'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/reset-password'
    | '/signin'
    | '/signup'
    | '/unauthorized'
    | '/about'
    | '/contact'
    | '/home'
    | '/pricing'
    | '/privacy-policy'
    | '/terms-of-service'
    | '/docs'
    | '/admin/audit-trails'
    | '/admin/compliance'
    | '/admin/flagged'
    | '/admin/support'
    | '/audit/overview'
    | '/audit/payments'
    | '/audit/settings'
    | '/audit/statements'
    | '/audit/support'
    | '/dashboard/cards'
    | '/dashboard/overview'
    | '/dashboard/payments'
    | '/dashboard/settings'
    | '/dashboard/statements'
    | '/dashboard/support'
    | '/dashboard/transactions'
    | '/manager/overview'
    | '/manager/payments'
    | '/manager/settings'
    | '/manager/statements'
    | '/manager/support'
    | '/owner/branches'
    | '/owner/reports'
    | '/owner/settings'
    | '/owner/staff-performance'
    | '/staff/overview'
    | '/staff/payments'
    | '/staff/settings'
    | '/staff/statements'
    | '/staff/support'
    | '/superadmin/branches'
    | '/superadmin/employees'
    | '/superadmin/reports'
    | '/superadmin/settings'
    | '/support/overview'
    | '/support/payments'
    | '/support/settings'
    | '/support/statements'
    | '/support/support'
  id:
    | '__root__'
    | '/'
    | '/(auth)/forgot-password'
    | '/(auth)/reset-password'
    | '/(auth)/signin'
    | '/(auth)/signup'
    | '/(auth)/unauthorized'
    | '/(landing)/about'
    | '/(landing)/contact'
    | '/(landing)/home'
    | '/(landing)/pricing'
    | '/(landing)/privacy-policy'
    | '/(landing)/terms-of-service'
    | '/docs/'
    | '/(dashboard)/admin/audit-trails'
    | '/(dashboard)/admin/compliance'
    | '/(dashboard)/admin/flagged'
    | '/(dashboard)/admin/support'
    | '/(dashboard)/audit/overview'
    | '/(dashboard)/audit/payments'
    | '/(dashboard)/audit/settings'
    | '/(dashboard)/audit/statements'
    | '/(dashboard)/audit/support'
    | '/(dashboard)/dashboard/cards'
    | '/(dashboard)/dashboard/overview'
    | '/(dashboard)/dashboard/payments'
    | '/(dashboard)/dashboard/settings'
    | '/(dashboard)/dashboard/statements'
    | '/(dashboard)/dashboard/support'
    | '/(dashboard)/dashboard/transactions'
    | '/(dashboard)/manager/overview'
    | '/(dashboard)/manager/payments'
    | '/(dashboard)/manager/settings'
    | '/(dashboard)/manager/statements'
    | '/(dashboard)/manager/support'
    | '/(dashboard)/owner/branches'
    | '/(dashboard)/owner/reports'
    | '/(dashboard)/owner/settings'
    | '/(dashboard)/owner/staff-performance'
    | '/(dashboard)/staff/overview'
    | '/(dashboard)/staff/payments'
    | '/(dashboard)/staff/settings'
    | '/(dashboard)/staff/statements'
    | '/(dashboard)/staff/support'
    | '/(dashboard)/superadmin/branches'
    | '/(dashboard)/superadmin/employees'
    | '/(dashboard)/superadmin/reports'
    | '/(dashboard)/superadmin/settings'
    | '/(dashboard)/support/overview'
    | '/(dashboard)/support/payments'
    | '/(dashboard)/support/settings'
    | '/(dashboard)/support/statements'
    | '/(dashboard)/support/support'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authResetPasswordRoute: typeof authResetPasswordRoute
  authSigninRoute: typeof authSigninRoute
  authSignupRoute: typeof authSignupRoute
  authUnauthorizedRoute: typeof authUnauthorizedRoute
  landingAboutRoute: typeof landingAboutRoute
  landingContactRoute: typeof landingContactRoute
  landingHomeRoute: typeof landingHomeRoute
  landingPricingRoute: typeof landingPricingRoute
  landingPrivacyPolicyRoute: typeof landingPrivacyPolicyRoute
  landingTermsOfServiceRoute: typeof landingTermsOfServiceRoute
  DocsIndexRoute: typeof DocsIndexRoute
  dashboardAdminAuditTrailsRoute: typeof dashboardAdminAuditTrailsRoute
  dashboardAdminComplianceRoute: typeof dashboardAdminComplianceRoute
  dashboardAdminFlaggedRoute: typeof dashboardAdminFlaggedRoute
  dashboardAdminSupportRoute: typeof dashboardAdminSupportRoute
  dashboardAuditOverviewRoute: typeof dashboardAuditOverviewRoute
  dashboardAuditPaymentsRoute: typeof dashboardAuditPaymentsRoute
  dashboardAuditSettingsRoute: typeof dashboardAuditSettingsRoute
  dashboardAuditStatementsRoute: typeof dashboardAuditStatementsRoute
  dashboardAuditSupportRoute: typeof dashboardAuditSupportRoute
  dashboardDashboardCardsRoute: typeof dashboardDashboardCardsRoute
  dashboardDashboardOverviewRoute: typeof dashboardDashboardOverviewRoute
  dashboardDashboardPaymentsRoute: typeof dashboardDashboardPaymentsRoute
  dashboardDashboardSettingsRoute: typeof dashboardDashboardSettingsRoute
  dashboardDashboardStatementsRoute: typeof dashboardDashboardStatementsRoute
  dashboardDashboardSupportRoute: typeof dashboardDashboardSupportRoute
  dashboardDashboardTransactionsRoute: typeof dashboardDashboardTransactionsRoute
  dashboardManagerOverviewRoute: typeof dashboardManagerOverviewRoute
  dashboardManagerPaymentsRoute: typeof dashboardManagerPaymentsRoute
  dashboardManagerSettingsRoute: typeof dashboardManagerSettingsRoute
  dashboardManagerStatementsRoute: typeof dashboardManagerStatementsRoute
  dashboardManagerSupportRoute: typeof dashboardManagerSupportRoute
  dashboardOwnerBranchesRoute: typeof dashboardOwnerBranchesRoute
  dashboardOwnerReportsRoute: typeof dashboardOwnerReportsRoute
  dashboardOwnerSettingsRoute: typeof dashboardOwnerSettingsRoute
  dashboardOwnerStaffPerformanceRoute: typeof dashboardOwnerStaffPerformanceRoute
  dashboardStaffOverviewRoute: typeof dashboardStaffOverviewRoute
  dashboardStaffPaymentsRoute: typeof dashboardStaffPaymentsRoute
  dashboardStaffSettingsRoute: typeof dashboardStaffSettingsRoute
  dashboardStaffStatementsRoute: typeof dashboardStaffStatementsRoute
  dashboardStaffSupportRoute: typeof dashboardStaffSupportRoute
  dashboardSuperadminBranchesRoute: typeof dashboardSuperadminBranchesRoute
  dashboardSuperadminEmployeesRoute: typeof dashboardSuperadminEmployeesRoute
  dashboardSuperadminReportsRoute: typeof dashboardSuperadminReportsRoute
  dashboardSuperadminSettingsRoute: typeof dashboardSuperadminSettingsRoute
  dashboardSupportOverviewRoute: typeof dashboardSupportOverviewRoute
  dashboardSupportPaymentsRoute: typeof dashboardSupportPaymentsRoute
  dashboardSupportSettingsRoute: typeof dashboardSupportSettingsRoute
  dashboardSupportStatementsRoute: typeof dashboardSupportStatementsRoute
  dashboardSupportSupportRoute: typeof dashboardSupportSupportRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(landing)/terms-of-service': {
      id: '/(landing)/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/terms-of-service'
      preLoaderRoute: typeof landingTermsOfServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(landing)/privacy-policy': {
      id: '/(landing)/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof landingPrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(landing)/pricing': {
      id: '/(landing)/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof landingPricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(landing)/home': {
      id: '/(landing)/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof landingHomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(landing)/contact': {
      id: '/(landing)/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof landingContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(landing)/about': {
      id: '/(landing)/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof landingAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/unauthorized': {
      id: '/(auth)/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof authUnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/signup': {
      id: '/(auth)/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof authSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/signin': {
      id: '/(auth)/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof authSigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/reset-password': {
      id: '/(auth)/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof authResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/support/support': {
      id: '/(dashboard)/support/support'
      path: '/support/support'
      fullPath: '/support/support'
      preLoaderRoute: typeof dashboardSupportSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/support/statements': {
      id: '/(dashboard)/support/statements'
      path: '/support/statements'
      fullPath: '/support/statements'
      preLoaderRoute: typeof dashboardSupportStatementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/support/settings': {
      id: '/(dashboard)/support/settings'
      path: '/support/settings'
      fullPath: '/support/settings'
      preLoaderRoute: typeof dashboardSupportSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/support/payments': {
      id: '/(dashboard)/support/payments'
      path: '/support/payments'
      fullPath: '/support/payments'
      preLoaderRoute: typeof dashboardSupportPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/support/overview': {
      id: '/(dashboard)/support/overview'
      path: '/support/overview'
      fullPath: '/support/overview'
      preLoaderRoute: typeof dashboardSupportOverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/superadmin/settings': {
      id: '/(dashboard)/superadmin/settings'
      path: '/superadmin/settings'
      fullPath: '/superadmin/settings'
      preLoaderRoute: typeof dashboardSuperadminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/superadmin/reports': {
      id: '/(dashboard)/superadmin/reports'
      path: '/superadmin/reports'
      fullPath: '/superadmin/reports'
      preLoaderRoute: typeof dashboardSuperadminReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/superadmin/employees': {
      id: '/(dashboard)/superadmin/employees'
      path: '/superadmin/employees'
      fullPath: '/superadmin/employees'
      preLoaderRoute: typeof dashboardSuperadminEmployeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/superadmin/branches': {
      id: '/(dashboard)/superadmin/branches'
      path: '/superadmin/branches'
      fullPath: '/superadmin/branches'
      preLoaderRoute: typeof dashboardSuperadminBranchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/staff/support': {
      id: '/(dashboard)/staff/support'
      path: '/staff/support'
      fullPath: '/staff/support'
      preLoaderRoute: typeof dashboardStaffSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/staff/statements': {
      id: '/(dashboard)/staff/statements'
      path: '/staff/statements'
      fullPath: '/staff/statements'
      preLoaderRoute: typeof dashboardStaffStatementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/staff/settings': {
      id: '/(dashboard)/staff/settings'
      path: '/staff/settings'
      fullPath: '/staff/settings'
      preLoaderRoute: typeof dashboardStaffSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/staff/payments': {
      id: '/(dashboard)/staff/payments'
      path: '/staff/payments'
      fullPath: '/staff/payments'
      preLoaderRoute: typeof dashboardStaffPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/staff/overview': {
      id: '/(dashboard)/staff/overview'
      path: '/staff/overview'
      fullPath: '/staff/overview'
      preLoaderRoute: typeof dashboardStaffOverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/owner/staff-performance': {
      id: '/(dashboard)/owner/staff-performance'
      path: '/owner/staff-performance'
      fullPath: '/owner/staff-performance'
      preLoaderRoute: typeof dashboardOwnerStaffPerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/owner/settings': {
      id: '/(dashboard)/owner/settings'
      path: '/owner/settings'
      fullPath: '/owner/settings'
      preLoaderRoute: typeof dashboardOwnerSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/owner/reports': {
      id: '/(dashboard)/owner/reports'
      path: '/owner/reports'
      fullPath: '/owner/reports'
      preLoaderRoute: typeof dashboardOwnerReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/owner/branches': {
      id: '/(dashboard)/owner/branches'
      path: '/owner/branches'
      fullPath: '/owner/branches'
      preLoaderRoute: typeof dashboardOwnerBranchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/manager/support': {
      id: '/(dashboard)/manager/support'
      path: '/manager/support'
      fullPath: '/manager/support'
      preLoaderRoute: typeof dashboardManagerSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/manager/statements': {
      id: '/(dashboard)/manager/statements'
      path: '/manager/statements'
      fullPath: '/manager/statements'
      preLoaderRoute: typeof dashboardManagerStatementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/manager/settings': {
      id: '/(dashboard)/manager/settings'
      path: '/manager/settings'
      fullPath: '/manager/settings'
      preLoaderRoute: typeof dashboardManagerSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/manager/payments': {
      id: '/(dashboard)/manager/payments'
      path: '/manager/payments'
      fullPath: '/manager/payments'
      preLoaderRoute: typeof dashboardManagerPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/manager/overview': {
      id: '/(dashboard)/manager/overview'
      path: '/manager/overview'
      fullPath: '/manager/overview'
      preLoaderRoute: typeof dashboardManagerOverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/dashboard/transactions': {
      id: '/(dashboard)/dashboard/transactions'
      path: '/dashboard/transactions'
      fullPath: '/dashboard/transactions'
      preLoaderRoute: typeof dashboardDashboardTransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/dashboard/support': {
      id: '/(dashboard)/dashboard/support'
      path: '/dashboard/support'
      fullPath: '/dashboard/support'
      preLoaderRoute: typeof dashboardDashboardSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/dashboard/statements': {
      id: '/(dashboard)/dashboard/statements'
      path: '/dashboard/statements'
      fullPath: '/dashboard/statements'
      preLoaderRoute: typeof dashboardDashboardStatementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/dashboard/settings': {
      id: '/(dashboard)/dashboard/settings'
      path: '/dashboard/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof dashboardDashboardSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/dashboard/payments': {
      id: '/(dashboard)/dashboard/payments'
      path: '/dashboard/payments'
      fullPath: '/dashboard/payments'
      preLoaderRoute: typeof dashboardDashboardPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/dashboard/overview': {
      id: '/(dashboard)/dashboard/overview'
      path: '/dashboard/overview'
      fullPath: '/dashboard/overview'
      preLoaderRoute: typeof dashboardDashboardOverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/dashboard/cards': {
      id: '/(dashboard)/dashboard/cards'
      path: '/dashboard/cards'
      fullPath: '/dashboard/cards'
      preLoaderRoute: typeof dashboardDashboardCardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/audit/support': {
      id: '/(dashboard)/audit/support'
      path: '/audit/support'
      fullPath: '/audit/support'
      preLoaderRoute: typeof dashboardAuditSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/audit/statements': {
      id: '/(dashboard)/audit/statements'
      path: '/audit/statements'
      fullPath: '/audit/statements'
      preLoaderRoute: typeof dashboardAuditStatementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/audit/settings': {
      id: '/(dashboard)/audit/settings'
      path: '/audit/settings'
      fullPath: '/audit/settings'
      preLoaderRoute: typeof dashboardAuditSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/audit/payments': {
      id: '/(dashboard)/audit/payments'
      path: '/audit/payments'
      fullPath: '/audit/payments'
      preLoaderRoute: typeof dashboardAuditPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/audit/overview': {
      id: '/(dashboard)/audit/overview'
      path: '/audit/overview'
      fullPath: '/audit/overview'
      preLoaderRoute: typeof dashboardAuditOverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/admin/support': {
      id: '/(dashboard)/admin/support'
      path: '/admin/support'
      fullPath: '/admin/support'
      preLoaderRoute: typeof dashboardAdminSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/admin/flagged': {
      id: '/(dashboard)/admin/flagged'
      path: '/admin/flagged'
      fullPath: '/admin/flagged'
      preLoaderRoute: typeof dashboardAdminFlaggedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/admin/compliance': {
      id: '/(dashboard)/admin/compliance'
      path: '/admin/compliance'
      fullPath: '/admin/compliance'
      preLoaderRoute: typeof dashboardAdminComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/admin/audit-trails': {
      id: '/(dashboard)/admin/audit-trails'
      path: '/admin/audit-trails'
      fullPath: '/admin/audit-trails'
      preLoaderRoute: typeof dashboardAdminAuditTrailsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authResetPasswordRoute: authResetPasswordRoute,
  authSigninRoute: authSigninRoute,
  authSignupRoute: authSignupRoute,
  authUnauthorizedRoute: authUnauthorizedRoute,
  landingAboutRoute: landingAboutRoute,
  landingContactRoute: landingContactRoute,
  landingHomeRoute: landingHomeRoute,
  landingPricingRoute: landingPricingRoute,
  landingPrivacyPolicyRoute: landingPrivacyPolicyRoute,
  landingTermsOfServiceRoute: landingTermsOfServiceRoute,
  DocsIndexRoute: DocsIndexRoute,
  dashboardAdminAuditTrailsRoute: dashboardAdminAuditTrailsRoute,
  dashboardAdminComplianceRoute: dashboardAdminComplianceRoute,
  dashboardAdminFlaggedRoute: dashboardAdminFlaggedRoute,
  dashboardAdminSupportRoute: dashboardAdminSupportRoute,
  dashboardAuditOverviewRoute: dashboardAuditOverviewRoute,
  dashboardAuditPaymentsRoute: dashboardAuditPaymentsRoute,
  dashboardAuditSettingsRoute: dashboardAuditSettingsRoute,
  dashboardAuditStatementsRoute: dashboardAuditStatementsRoute,
  dashboardAuditSupportRoute: dashboardAuditSupportRoute,
  dashboardDashboardCardsRoute: dashboardDashboardCardsRoute,
  dashboardDashboardOverviewRoute: dashboardDashboardOverviewRoute,
  dashboardDashboardPaymentsRoute: dashboardDashboardPaymentsRoute,
  dashboardDashboardSettingsRoute: dashboardDashboardSettingsRoute,
  dashboardDashboardStatementsRoute: dashboardDashboardStatementsRoute,
  dashboardDashboardSupportRoute: dashboardDashboardSupportRoute,
  dashboardDashboardTransactionsRoute: dashboardDashboardTransactionsRoute,
  dashboardManagerOverviewRoute: dashboardManagerOverviewRoute,
  dashboardManagerPaymentsRoute: dashboardManagerPaymentsRoute,
  dashboardManagerSettingsRoute: dashboardManagerSettingsRoute,
  dashboardManagerStatementsRoute: dashboardManagerStatementsRoute,
  dashboardManagerSupportRoute: dashboardManagerSupportRoute,
  dashboardOwnerBranchesRoute: dashboardOwnerBranchesRoute,
  dashboardOwnerReportsRoute: dashboardOwnerReportsRoute,
  dashboardOwnerSettingsRoute: dashboardOwnerSettingsRoute,
  dashboardOwnerStaffPerformanceRoute: dashboardOwnerStaffPerformanceRoute,
  dashboardStaffOverviewRoute: dashboardStaffOverviewRoute,
  dashboardStaffPaymentsRoute: dashboardStaffPaymentsRoute,
  dashboardStaffSettingsRoute: dashboardStaffSettingsRoute,
  dashboardStaffStatementsRoute: dashboardStaffStatementsRoute,
  dashboardStaffSupportRoute: dashboardStaffSupportRoute,
  dashboardSuperadminBranchesRoute: dashboardSuperadminBranchesRoute,
  dashboardSuperadminEmployeesRoute: dashboardSuperadminEmployeesRoute,
  dashboardSuperadminReportsRoute: dashboardSuperadminReportsRoute,
  dashboardSuperadminSettingsRoute: dashboardSuperadminSettingsRoute,
  dashboardSupportOverviewRoute: dashboardSupportOverviewRoute,
  dashboardSupportPaymentsRoute: dashboardSupportPaymentsRoute,
  dashboardSupportSettingsRoute: dashboardSupportSettingsRoute,
  dashboardSupportStatementsRoute: dashboardSupportStatementsRoute,
  dashboardSupportSupportRoute: dashboardSupportSupportRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
