/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DocsIndexRouteImport } from './routes/docs/index'
import { Route as landingIndexRouteImport } from './routes/(landing)/index'
import { Route as DocsSplatRouteImport } from './routes/docs/$'
import { Route as ApiSearchRouteImport } from './routes/api/search'
import { Route as landingTermsOfServiceRouteImport } from './routes/(landing)/terms-of-service'
import { Route as landingSecurityRouteImport } from './routes/(landing)/security'
import { Route as landingPrivacyPolicyRouteImport } from './routes/(landing)/privacy-policy'
import { Route as landingPricingRouteImport } from './routes/(landing)/pricing'
import { Route as landingHowItWorksRouteImport } from './routes/(landing)/how-it-works'
import { Route as landingHomeRouteImport } from './routes/(landing)/home'
import { Route as landingFeaturesRouteImport } from './routes/(landing)/features'
import { Route as landingContactRouteImport } from './routes/(landing)/contact'
import { Route as landingAboutRouteImport } from './routes/(landing)/about'
import { Route as dashboardTransactionsRouteImport } from './routes/(dashboard)/transactions'
import { Route as dashboardSupportRouteImport } from './routes/(dashboard)/support'
import { Route as dashboardSettingsRouteImport } from './routes/(dashboard)/settings'
import { Route as dashboardReportsRouteImport } from './routes/(dashboard)/reports'
import { Route as dashboardOverviewRouteImport } from './routes/(dashboard)/overview'
import { Route as dashboardDashboardRouteImport } from './routes/(dashboard)/dashboard'
import { Route as dashboardCardsRouteImport } from './routes/(dashboard)/cards'
import { Route as dashboardAccountsRouteImport } from './routes/(dashboard)/accounts'
import { Route as authUnauthorizedRouteImport } from './routes/(auth)/unauthorized'
import { Route as authSignupRouteImport } from './routes/(auth)/signup'
import { Route as authSigninRouteImport } from './routes/(auth)/signin'
import { Route as authResetPasswordRouteImport } from './routes/(auth)/reset-password'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as dashboardSuperadminIndexRouteImport } from './routes/(dashboard)/superadmin/index'
import { Route as dashboardOwnerIndexRouteImport } from './routes/(dashboard)/owner/index'
import { Route as DemoStartServerFuncsRouteImport } from './routes/demo/start.server-funcs'
import { Route as DemoStartApiRequestRouteImport } from './routes/demo/start.api-request'
import { Route as DemoApiNamesRouteImport } from './routes/demo/api.names'
import { Route as dashboardSupportSupportRouteImport } from './routes/(dashboard)/support/support'
import { Route as dashboardSupportStatementsRouteImport } from './routes/(dashboard)/support/statements'
import { Route as dashboardSupportSettingsRouteImport } from './routes/(dashboard)/support/settings'
import { Route as dashboardSupportPaymentsRouteImport } from './routes/(dashboard)/support/payments'
import { Route as dashboardSupportOverviewRouteImport } from './routes/(dashboard)/support/overview'
import { Route as dashboardSuperadminSettingsRouteImport } from './routes/(dashboard)/superadmin/settings'
import { Route as dashboardSuperadminReportsRouteImport } from './routes/(dashboard)/superadmin/reports'
import { Route as dashboardSuperadminOverviewRouteImport } from './routes/(dashboard)/superadmin/overview'
import { Route as dashboardSuperadminEmployeesRouteImport } from './routes/(dashboard)/superadmin/employees'
import { Route as dashboardSuperadminBranchesRouteImport } from './routes/(dashboard)/superadmin/branches'
import { Route as dashboardStaffSupportRouteImport } from './routes/(dashboard)/staff/support'
import { Route as dashboardStaffStatementsRouteImport } from './routes/(dashboard)/staff/statements'
import { Route as dashboardStaffSettingsRouteImport } from './routes/(dashboard)/staff/settings'
import { Route as dashboardStaffPaymentsRouteImport } from './routes/(dashboard)/staff/payments'
import { Route as dashboardStaffOverviewRouteImport } from './routes/(dashboard)/staff/overview'
import { Route as dashboardOwnerStaffPerformanceRouteImport } from './routes/(dashboard)/owner/staff-performance'
import { Route as dashboardOwnerSettingsRouteImport } from './routes/(dashboard)/owner/settings'
import { Route as dashboardOwnerReportsRouteImport } from './routes/(dashboard)/owner/reports'
import { Route as dashboardOwnerOverviewRouteImport } from './routes/(dashboard)/owner/overview'
import { Route as dashboardOwnerBranchesRouteImport } from './routes/(dashboard)/owner/branches'
import { Route as dashboardManagerSupportRouteImport } from './routes/(dashboard)/manager/support'
import { Route as dashboardManagerStatementsRouteImport } from './routes/(dashboard)/manager/statements'
import { Route as dashboardManagerSettingsRouteImport } from './routes/(dashboard)/manager/settings'
import { Route as dashboardManagerPaymentsRouteImport } from './routes/(dashboard)/manager/payments'
import { Route as dashboardManagerOverviewRouteImport } from './routes/(dashboard)/manager/overview'
import { Route as dashboardDashboardTransactionsRouteImport } from './routes/(dashboard)/dashboard/transactions'
import { Route as dashboardDashboardSupportRouteImport } from './routes/(dashboard)/dashboard/support'
import { Route as dashboardDashboardStatementsRouteImport } from './routes/(dashboard)/dashboard/statements'
import { Route as dashboardDashboardSettingsRouteImport } from './routes/(dashboard)/dashboard/settings'
import { Route as dashboardDashboardPaymentsRouteImport } from './routes/(dashboard)/dashboard/payments'
import { Route as dashboardDashboardOverviewRouteImport } from './routes/(dashboard)/dashboard/overview'
import { Route as dashboardDashboardCardsRouteImport } from './routes/(dashboard)/dashboard/cards'
import { Route as dashboardAuditSupportRouteImport } from './routes/(dashboard)/audit/support'
import { Route as dashboardAuditStatementsRouteImport } from './routes/(dashboard)/audit/statements'
import { Route as dashboardAuditSettingsRouteImport } from './routes/(dashboard)/audit/settings'
import { Route as dashboardAuditPaymentsRouteImport } from './routes/(dashboard)/audit/payments'
import { Route as dashboardAuditOverviewRouteImport } from './routes/(dashboard)/audit/overview'
import { Route as dashboardAdminSupportRouteImport } from './routes/(dashboard)/admin/support'
import { Route as dashboardAdminFlaggedRouteImport } from './routes/(dashboard)/admin/flagged'
import { Route as dashboardAdminComplianceRouteImport } from './routes/(dashboard)/admin/compliance'
import { Route as dashboardAdminAuditTrailsRouteImport } from './routes/(dashboard)/admin/audit-trails'
import { Route as DemoStartSsrIndexRouteImport } from './routes/demo/start.ssr.index'
import { Route as DemoStartSsrSpaModeRouteImport } from './routes/demo/start.ssr.spa-mode'
import { Route as DemoStartSsrFullSsrRouteImport } from './routes/demo/start.ssr.full-ssr'
import { Route as DemoStartSsrDataOnlyRouteImport } from './routes/demo/start.ssr.data-only'

const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/docs/',
  path: '/docs/',
  getParentRoute: () => rootRouteImport,
} as any)
const landingIndexRoute = landingIndexRouteImport.update({
  id: '/(landing)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsSplatRoute = DocsSplatRouteImport.update({
  id: '/docs/$',
  path: '/docs/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSearchRoute = ApiSearchRouteImport.update({
  id: '/api/search',
  path: '/api/search',
  getParentRoute: () => rootRouteImport,
} as any)
const landingTermsOfServiceRoute = landingTermsOfServiceRouteImport.update({
  id: '/(landing)/terms-of-service',
  path: '/terms-of-service',
  getParentRoute: () => rootRouteImport,
} as any)
const landingSecurityRoute = landingSecurityRouteImport.update({
  id: '/(landing)/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const landingPrivacyPolicyRoute = landingPrivacyPolicyRouteImport.update({
  id: '/(landing)/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const landingPricingRoute = landingPricingRouteImport.update({
  id: '/(landing)/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const landingHowItWorksRoute = landingHowItWorksRouteImport.update({
  id: '/(landing)/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const landingHomeRoute = landingHomeRouteImport.update({
  id: '/(landing)/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const landingFeaturesRoute = landingFeaturesRouteImport.update({
  id: '/(landing)/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const landingContactRoute = landingContactRouteImport.update({
  id: '/(landing)/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const landingAboutRoute = landingAboutRouteImport.update({
  id: '/(landing)/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboardTransactionsRoute = dashboardTransactionsRouteImport.update({
  id: '/(dashboard)/transactions',
  path: '/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboardSupportRoute = dashboardSupportRouteImport.update({
  id: '/(dashboard)/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboardSettingsRoute = dashboardSettingsRouteImport.update({
  id: '/(dashboard)/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboardReportsRoute = dashboardReportsRouteImport.update({
  id: '/(dashboard)/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboardOverviewRoute = dashboardOverviewRouteImport.update({
  id: '/(dashboard)/overview',
  path: '/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboardDashboardRoute = dashboardDashboardRouteImport.update({
  id: '/(dashboard)/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboardCardsRoute = dashboardCardsRouteImport.update({
  id: '/(dashboard)/cards',
  path: '/cards',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboardAccountsRoute = dashboardAccountsRouteImport.update({
  id: '/(dashboard)/accounts',
  path: '/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const authUnauthorizedRoute = authUnauthorizedRouteImport.update({
  id: '/(auth)/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignupRoute = authSignupRouteImport.update({
  id: '/(auth)/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const authSigninRoute = authSigninRouteImport.update({
  id: '/(auth)/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const authResetPasswordRoute = authResetPasswordRouteImport.update({
  id: '/(auth)/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboardSuperadminIndexRoute =
  dashboardSuperadminIndexRouteImport.update({
    id: '/(dashboard)/superadmin/',
    path: '/superadmin/',
    getParentRoute: () => rootRouteImport,
  } as any)
const dashboardOwnerIndexRoute = dashboardOwnerIndexRouteImport.update({
  id: '/(dashboard)/owner/',
  path: '/owner/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartServerFuncsRoute = DemoStartServerFuncsRouteImport.update({
  id: '/demo/start/server-funcs',
  path: '/demo/start/server-funcs',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartApiRequestRoute = DemoStartApiRequestRouteImport.update({
  id: '/demo/start/api-request',
  path: '/demo/start/api-request',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiNamesRoute = DemoApiNamesRouteImport.update({
  id: '/demo/api/names',
  path: '/demo/api/names',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboardSupportSupportRoute = dashboardSupportSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => dashboardSupportRoute,
} as any)
const dashboardSupportStatementsRoute =
  dashboardSupportStatementsRouteImport.update({
    id: '/statements',
    path: '/statements',
    getParentRoute: () => dashboardSupportRoute,
  } as any)
const dashboardSupportSettingsRoute =
  dashboardSupportSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => dashboardSupportRoute,
  } as any)
const dashboardSupportPaymentsRoute =
  dashboardSupportPaymentsRouteImport.update({
    id: '/payments',
    path: '/payments',
    getParentRoute: () => dashboardSupportRoute,
  } as any)
const dashboardSupportOverviewRoute =
  dashboardSupportOverviewRouteImport.update({
    id: '/overview',
    path: '/overview',
    getParentRoute: () => dashboardSupportRoute,
  } as any)
const dashboardSuperadminSettingsRoute =
  dashboardSuperadminSettingsRouteImport.update({
    id: '/(dashboard)/superadmin/settings',
    path: '/superadmin/settings',
    getParentRoute: () => rootRouteImport,
  } as any)
const dashboardSuperadminReportsRoute =
  dashboardSuperadminReportsRouteImport.update({
    id: '/(dashboard)/superadmin/reports',
    path: '/superadmin/reports',
    getParentRoute: () => rootRouteImport,
  } as any)
const dashboardSuperadminOverviewRoute =
  dashboardSuperadminOverviewRouteImport.update({
    id: '/(dashboard)/superadmin/overview',
    path: '/superadmin/overview',
    getParentRoute: () => rootRouteImport,
  } as any)
const dashboardSuperadminEmployeesRoute =
  dashboardSuperadminEmployeesRouteImport.update({
    id: '/(dashboard)/superadmin/employees',
    path: '/superadmin/employees',
    getParentRoute: () => rootRouteImport,
  } as any)
const dashboardSuperadminBranchesRoute =
  dashboardSuperadminBranchesRouteImport.update({
    id: '/(dashboard)/superadmin/branches',
    path: '/superadmin/branches',
    getParentRoute: () => rootRouteImport,
  } as any)
const dashboardStaffSupportRoute = dashboardStaffSupportRouteImport.update({
  id: '/(dashboard)/staff/support',
  path: '/staff/support',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboardStaffStatementsRoute =
  dashboardStaffStatementsRouteImport.update({
    id: '/(dashboard)/staff/statements',
    path: '/staff/statements',
    getParentRoute: () => rootRouteImport,
  } as any)
const dashboardStaffSettingsRoute = dashboardStaffSettingsRouteImport.update({
  id: '/(dashboard)/staff/settings',
  path: '/staff/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboardStaffPaymentsRoute = dashboardStaffPaymentsRouteImport.update({
  id: '/(dashboard)/staff/payments',
  path: '/staff/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboardStaffOverviewRoute = dashboardStaffOverviewRouteImport.update({
  id: '/(dashboard)/staff/overview',
  path: '/staff/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboardOwnerStaffPerformanceRoute =
  dashboardOwnerStaffPerformanceRouteImport.update({
    id: '/(dashboard)/owner/staff-performance',
    path: '/owner/staff-performance',
    getParentRoute: () => rootRouteImport,
  } as any)
const dashboardOwnerSettingsRoute = dashboardOwnerSettingsRouteImport.update({
  id: '/(dashboard)/owner/settings',
  path: '/owner/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboardOwnerReportsRoute = dashboardOwnerReportsRouteImport.update({
  id: '/(dashboard)/owner/reports',
  path: '/owner/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboardOwnerOverviewRoute = dashboardOwnerOverviewRouteImport.update({
  id: '/(dashboard)/owner/overview',
  path: '/owner/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboardOwnerBranchesRoute = dashboardOwnerBranchesRouteImport.update({
  id: '/(dashboard)/owner/branches',
  path: '/owner/branches',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboardManagerSupportRoute = dashboardManagerSupportRouteImport.update({
  id: '/(dashboard)/manager/support',
  path: '/manager/support',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboardManagerStatementsRoute =
  dashboardManagerStatementsRouteImport.update({
    id: '/(dashboard)/manager/statements',
    path: '/manager/statements',
    getParentRoute: () => rootRouteImport,
  } as any)
const dashboardManagerSettingsRoute =
  dashboardManagerSettingsRouteImport.update({
    id: '/(dashboard)/manager/settings',
    path: '/manager/settings',
    getParentRoute: () => rootRouteImport,
  } as any)
const dashboardManagerPaymentsRoute =
  dashboardManagerPaymentsRouteImport.update({
    id: '/(dashboard)/manager/payments',
    path: '/manager/payments',
    getParentRoute: () => rootRouteImport,
  } as any)
const dashboardManagerOverviewRoute =
  dashboardManagerOverviewRouteImport.update({
    id: '/(dashboard)/manager/overview',
    path: '/manager/overview',
    getParentRoute: () => rootRouteImport,
  } as any)
const dashboardDashboardTransactionsRoute =
  dashboardDashboardTransactionsRouteImport.update({
    id: '/transactions',
    path: '/transactions',
    getParentRoute: () => dashboardDashboardRoute,
  } as any)
const dashboardDashboardSupportRoute =
  dashboardDashboardSupportRouteImport.update({
    id: '/support',
    path: '/support',
    getParentRoute: () => dashboardDashboardRoute,
  } as any)
const dashboardDashboardStatementsRoute =
  dashboardDashboardStatementsRouteImport.update({
    id: '/statements',
    path: '/statements',
    getParentRoute: () => dashboardDashboardRoute,
  } as any)
const dashboardDashboardSettingsRoute =
  dashboardDashboardSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => dashboardDashboardRoute,
  } as any)
const dashboardDashboardPaymentsRoute =
  dashboardDashboardPaymentsRouteImport.update({
    id: '/payments',
    path: '/payments',
    getParentRoute: () => dashboardDashboardRoute,
  } as any)
const dashboardDashboardOverviewRoute =
  dashboardDashboardOverviewRouteImport.update({
    id: '/overview',
    path: '/overview',
    getParentRoute: () => dashboardDashboardRoute,
  } as any)
const dashboardDashboardCardsRoute = dashboardDashboardCardsRouteImport.update({
  id: '/cards',
  path: '/cards',
  getParentRoute: () => dashboardDashboardRoute,
} as any)
const dashboardAuditSupportRoute = dashboardAuditSupportRouteImport.update({
  id: '/(dashboard)/audit/support',
  path: '/audit/support',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboardAuditStatementsRoute =
  dashboardAuditStatementsRouteImport.update({
    id: '/(dashboard)/audit/statements',
    path: '/audit/statements',
    getParentRoute: () => rootRouteImport,
  } as any)
const dashboardAuditSettingsRoute = dashboardAuditSettingsRouteImport.update({
  id: '/(dashboard)/audit/settings',
  path: '/audit/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboardAuditPaymentsRoute = dashboardAuditPaymentsRouteImport.update({
  id: '/(dashboard)/audit/payments',
  path: '/audit/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboardAuditOverviewRoute = dashboardAuditOverviewRouteImport.update({
  id: '/(dashboard)/audit/overview',
  path: '/audit/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboardAdminSupportRoute = dashboardAdminSupportRouteImport.update({
  id: '/(dashboard)/admin/support',
  path: '/admin/support',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboardAdminFlaggedRoute = dashboardAdminFlaggedRouteImport.update({
  id: '/(dashboard)/admin/flagged',
  path: '/admin/flagged',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboardAdminComplianceRoute =
  dashboardAdminComplianceRouteImport.update({
    id: '/(dashboard)/admin/compliance',
    path: '/admin/compliance',
    getParentRoute: () => rootRouteImport,
  } as any)
const dashboardAdminAuditTrailsRoute =
  dashboardAdminAuditTrailsRouteImport.update({
    id: '/(dashboard)/admin/audit-trails',
    path: '/admin/audit-trails',
    getParentRoute: () => rootRouteImport,
  } as any)
const DemoStartSsrIndexRoute = DemoStartSsrIndexRouteImport.update({
  id: '/demo/start/ssr/',
  path: '/demo/start/ssr/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrSpaModeRoute = DemoStartSsrSpaModeRouteImport.update({
  id: '/demo/start/ssr/spa-mode',
  path: '/demo/start/ssr/spa-mode',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrFullSsrRoute = DemoStartSsrFullSsrRouteImport.update({
  id: '/demo/start/ssr/full-ssr',
  path: '/demo/start/ssr/full-ssr',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrDataOnlyRoute = DemoStartSsrDataOnlyRouteImport.update({
  id: '/demo/start/ssr/data-only',
  path: '/demo/start/ssr/data-only',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/forgot-password': typeof authForgotPasswordRoute
  '/reset-password': typeof authResetPasswordRoute
  '/signin': typeof authSigninRoute
  '/signup': typeof authSignupRoute
  '/unauthorized': typeof authUnauthorizedRoute
  '/accounts': typeof dashboardAccountsRoute
  '/cards': typeof dashboardCardsRoute
  '/dashboard': typeof dashboardDashboardRouteWithChildren
  '/overview': typeof dashboardOverviewRoute
  '/reports': typeof dashboardReportsRoute
  '/settings': typeof dashboardSettingsRoute
  '/support': typeof dashboardSupportRouteWithChildren
  '/transactions': typeof dashboardTransactionsRoute
  '/about': typeof landingAboutRoute
  '/contact': typeof landingContactRoute
  '/features': typeof landingFeaturesRoute
  '/home': typeof landingHomeRoute
  '/how-it-works': typeof landingHowItWorksRoute
  '/pricing': typeof landingPricingRoute
  '/privacy-policy': typeof landingPrivacyPolicyRoute
  '/security': typeof landingSecurityRoute
  '/terms-of-service': typeof landingTermsOfServiceRoute
  '/api/search': typeof ApiSearchRoute
  '/docs/$': typeof DocsSplatRoute
  '/': typeof landingIndexRoute
  '/docs': typeof DocsIndexRoute
  '/admin/audit-trails': typeof dashboardAdminAuditTrailsRoute
  '/admin/compliance': typeof dashboardAdminComplianceRoute
  '/admin/flagged': typeof dashboardAdminFlaggedRoute
  '/admin/support': typeof dashboardAdminSupportRoute
  '/audit/overview': typeof dashboardAuditOverviewRoute
  '/audit/payments': typeof dashboardAuditPaymentsRoute
  '/audit/settings': typeof dashboardAuditSettingsRoute
  '/audit/statements': typeof dashboardAuditStatementsRoute
  '/audit/support': typeof dashboardAuditSupportRoute
  '/dashboard/cards': typeof dashboardDashboardCardsRoute
  '/dashboard/overview': typeof dashboardDashboardOverviewRoute
  '/dashboard/payments': typeof dashboardDashboardPaymentsRoute
  '/dashboard/settings': typeof dashboardDashboardSettingsRoute
  '/dashboard/statements': typeof dashboardDashboardStatementsRoute
  '/dashboard/support': typeof dashboardDashboardSupportRoute
  '/dashboard/transactions': typeof dashboardDashboardTransactionsRoute
  '/manager/overview': typeof dashboardManagerOverviewRoute
  '/manager/payments': typeof dashboardManagerPaymentsRoute
  '/manager/settings': typeof dashboardManagerSettingsRoute
  '/manager/statements': typeof dashboardManagerStatementsRoute
  '/manager/support': typeof dashboardManagerSupportRoute
  '/owner/branches': typeof dashboardOwnerBranchesRoute
  '/owner/overview': typeof dashboardOwnerOverviewRoute
  '/owner/reports': typeof dashboardOwnerReportsRoute
  '/owner/settings': typeof dashboardOwnerSettingsRoute
  '/owner/staff-performance': typeof dashboardOwnerStaffPerformanceRoute
  '/staff/overview': typeof dashboardStaffOverviewRoute
  '/staff/payments': typeof dashboardStaffPaymentsRoute
  '/staff/settings': typeof dashboardStaffSettingsRoute
  '/staff/statements': typeof dashboardStaffStatementsRoute
  '/staff/support': typeof dashboardStaffSupportRoute
  '/superadmin/branches': typeof dashboardSuperadminBranchesRoute
  '/superadmin/employees': typeof dashboardSuperadminEmployeesRoute
  '/superadmin/overview': typeof dashboardSuperadminOverviewRoute
  '/superadmin/reports': typeof dashboardSuperadminReportsRoute
  '/superadmin/settings': typeof dashboardSuperadminSettingsRoute
  '/support/overview': typeof dashboardSupportOverviewRoute
  '/support/payments': typeof dashboardSupportPaymentsRoute
  '/support/settings': typeof dashboardSupportSettingsRoute
  '/support/statements': typeof dashboardSupportStatementsRoute
  '/support/support': typeof dashboardSupportSupportRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/owner': typeof dashboardOwnerIndexRoute
  '/superadmin': typeof dashboardSuperadminIndexRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr': typeof DemoStartSsrIndexRoute
}
export interface FileRoutesByTo {
  '/forgot-password': typeof authForgotPasswordRoute
  '/reset-password': typeof authResetPasswordRoute
  '/signin': typeof authSigninRoute
  '/signup': typeof authSignupRoute
  '/unauthorized': typeof authUnauthorizedRoute
  '/accounts': typeof dashboardAccountsRoute
  '/cards': typeof dashboardCardsRoute
  '/dashboard': typeof dashboardDashboardRouteWithChildren
  '/overview': typeof dashboardOverviewRoute
  '/reports': typeof dashboardReportsRoute
  '/settings': typeof dashboardSettingsRoute
  '/support': typeof dashboardSupportRouteWithChildren
  '/transactions': typeof dashboardTransactionsRoute
  '/about': typeof landingAboutRoute
  '/contact': typeof landingContactRoute
  '/features': typeof landingFeaturesRoute
  '/home': typeof landingHomeRoute
  '/how-it-works': typeof landingHowItWorksRoute
  '/pricing': typeof landingPricingRoute
  '/privacy-policy': typeof landingPrivacyPolicyRoute
  '/security': typeof landingSecurityRoute
  '/terms-of-service': typeof landingTermsOfServiceRoute
  '/api/search': typeof ApiSearchRoute
  '/docs/$': typeof DocsSplatRoute
  '/': typeof landingIndexRoute
  '/docs': typeof DocsIndexRoute
  '/admin/audit-trails': typeof dashboardAdminAuditTrailsRoute
  '/admin/compliance': typeof dashboardAdminComplianceRoute
  '/admin/flagged': typeof dashboardAdminFlaggedRoute
  '/admin/support': typeof dashboardAdminSupportRoute
  '/audit/overview': typeof dashboardAuditOverviewRoute
  '/audit/payments': typeof dashboardAuditPaymentsRoute
  '/audit/settings': typeof dashboardAuditSettingsRoute
  '/audit/statements': typeof dashboardAuditStatementsRoute
  '/audit/support': typeof dashboardAuditSupportRoute
  '/dashboard/cards': typeof dashboardDashboardCardsRoute
  '/dashboard/overview': typeof dashboardDashboardOverviewRoute
  '/dashboard/payments': typeof dashboardDashboardPaymentsRoute
  '/dashboard/settings': typeof dashboardDashboardSettingsRoute
  '/dashboard/statements': typeof dashboardDashboardStatementsRoute
  '/dashboard/support': typeof dashboardDashboardSupportRoute
  '/dashboard/transactions': typeof dashboardDashboardTransactionsRoute
  '/manager/overview': typeof dashboardManagerOverviewRoute
  '/manager/payments': typeof dashboardManagerPaymentsRoute
  '/manager/settings': typeof dashboardManagerSettingsRoute
  '/manager/statements': typeof dashboardManagerStatementsRoute
  '/manager/support': typeof dashboardManagerSupportRoute
  '/owner/branches': typeof dashboardOwnerBranchesRoute
  '/owner/overview': typeof dashboardOwnerOverviewRoute
  '/owner/reports': typeof dashboardOwnerReportsRoute
  '/owner/settings': typeof dashboardOwnerSettingsRoute
  '/owner/staff-performance': typeof dashboardOwnerStaffPerformanceRoute
  '/staff/overview': typeof dashboardStaffOverviewRoute
  '/staff/payments': typeof dashboardStaffPaymentsRoute
  '/staff/settings': typeof dashboardStaffSettingsRoute
  '/staff/statements': typeof dashboardStaffStatementsRoute
  '/staff/support': typeof dashboardStaffSupportRoute
  '/superadmin/branches': typeof dashboardSuperadminBranchesRoute
  '/superadmin/employees': typeof dashboardSuperadminEmployeesRoute
  '/superadmin/overview': typeof dashboardSuperadminOverviewRoute
  '/superadmin/reports': typeof dashboardSuperadminReportsRoute
  '/superadmin/settings': typeof dashboardSuperadminSettingsRoute
  '/support/overview': typeof dashboardSupportOverviewRoute
  '/support/payments': typeof dashboardSupportPaymentsRoute
  '/support/settings': typeof dashboardSupportSettingsRoute
  '/support/statements': typeof dashboardSupportStatementsRoute
  '/support/support': typeof dashboardSupportSupportRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/owner': typeof dashboardOwnerIndexRoute
  '/superadmin': typeof dashboardSuperadminIndexRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr': typeof DemoStartSsrIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/reset-password': typeof authResetPasswordRoute
  '/(auth)/signin': typeof authSigninRoute
  '/(auth)/signup': typeof authSignupRoute
  '/(auth)/unauthorized': typeof authUnauthorizedRoute
  '/(dashboard)/accounts': typeof dashboardAccountsRoute
  '/(dashboard)/cards': typeof dashboardCardsRoute
  '/(dashboard)/dashboard': typeof dashboardDashboardRouteWithChildren
  '/(dashboard)/overview': typeof dashboardOverviewRoute
  '/(dashboard)/reports': typeof dashboardReportsRoute
  '/(dashboard)/settings': typeof dashboardSettingsRoute
  '/(dashboard)/support': typeof dashboardSupportRouteWithChildren
  '/(dashboard)/transactions': typeof dashboardTransactionsRoute
  '/(landing)/about': typeof landingAboutRoute
  '/(landing)/contact': typeof landingContactRoute
  '/(landing)/features': typeof landingFeaturesRoute
  '/(landing)/home': typeof landingHomeRoute
  '/(landing)/how-it-works': typeof landingHowItWorksRoute
  '/(landing)/pricing': typeof landingPricingRoute
  '/(landing)/privacy-policy': typeof landingPrivacyPolicyRoute
  '/(landing)/security': typeof landingSecurityRoute
  '/(landing)/terms-of-service': typeof landingTermsOfServiceRoute
  '/api/search': typeof ApiSearchRoute
  '/docs/$': typeof DocsSplatRoute
  '/(landing)/': typeof landingIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/(dashboard)/admin/audit-trails': typeof dashboardAdminAuditTrailsRoute
  '/(dashboard)/admin/compliance': typeof dashboardAdminComplianceRoute
  '/(dashboard)/admin/flagged': typeof dashboardAdminFlaggedRoute
  '/(dashboard)/admin/support': typeof dashboardAdminSupportRoute
  '/(dashboard)/audit/overview': typeof dashboardAuditOverviewRoute
  '/(dashboard)/audit/payments': typeof dashboardAuditPaymentsRoute
  '/(dashboard)/audit/settings': typeof dashboardAuditSettingsRoute
  '/(dashboard)/audit/statements': typeof dashboardAuditStatementsRoute
  '/(dashboard)/audit/support': typeof dashboardAuditSupportRoute
  '/(dashboard)/dashboard/cards': typeof dashboardDashboardCardsRoute
  '/(dashboard)/dashboard/overview': typeof dashboardDashboardOverviewRoute
  '/(dashboard)/dashboard/payments': typeof dashboardDashboardPaymentsRoute
  '/(dashboard)/dashboard/settings': typeof dashboardDashboardSettingsRoute
  '/(dashboard)/dashboard/statements': typeof dashboardDashboardStatementsRoute
  '/(dashboard)/dashboard/support': typeof dashboardDashboardSupportRoute
  '/(dashboard)/dashboard/transactions': typeof dashboardDashboardTransactionsRoute
  '/(dashboard)/manager/overview': typeof dashboardManagerOverviewRoute
  '/(dashboard)/manager/payments': typeof dashboardManagerPaymentsRoute
  '/(dashboard)/manager/settings': typeof dashboardManagerSettingsRoute
  '/(dashboard)/manager/statements': typeof dashboardManagerStatementsRoute
  '/(dashboard)/manager/support': typeof dashboardManagerSupportRoute
  '/(dashboard)/owner/branches': typeof dashboardOwnerBranchesRoute
  '/(dashboard)/owner/overview': typeof dashboardOwnerOverviewRoute
  '/(dashboard)/owner/reports': typeof dashboardOwnerReportsRoute
  '/(dashboard)/owner/settings': typeof dashboardOwnerSettingsRoute
  '/(dashboard)/owner/staff-performance': typeof dashboardOwnerStaffPerformanceRoute
  '/(dashboard)/staff/overview': typeof dashboardStaffOverviewRoute
  '/(dashboard)/staff/payments': typeof dashboardStaffPaymentsRoute
  '/(dashboard)/staff/settings': typeof dashboardStaffSettingsRoute
  '/(dashboard)/staff/statements': typeof dashboardStaffStatementsRoute
  '/(dashboard)/staff/support': typeof dashboardStaffSupportRoute
  '/(dashboard)/superadmin/branches': typeof dashboardSuperadminBranchesRoute
  '/(dashboard)/superadmin/employees': typeof dashboardSuperadminEmployeesRoute
  '/(dashboard)/superadmin/overview': typeof dashboardSuperadminOverviewRoute
  '/(dashboard)/superadmin/reports': typeof dashboardSuperadminReportsRoute
  '/(dashboard)/superadmin/settings': typeof dashboardSuperadminSettingsRoute
  '/(dashboard)/support/overview': typeof dashboardSupportOverviewRoute
  '/(dashboard)/support/payments': typeof dashboardSupportPaymentsRoute
  '/(dashboard)/support/settings': typeof dashboardSupportSettingsRoute
  '/(dashboard)/support/statements': typeof dashboardSupportStatementsRoute
  '/(dashboard)/support/support': typeof dashboardSupportSupportRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/(dashboard)/owner/': typeof dashboardOwnerIndexRoute
  '/(dashboard)/superadmin/': typeof dashboardSuperadminIndexRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr/': typeof DemoStartSsrIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/forgot-password'
    | '/reset-password'
    | '/signin'
    | '/signup'
    | '/unauthorized'
    | '/accounts'
    | '/cards'
    | '/dashboard'
    | '/overview'
    | '/reports'
    | '/settings'
    | '/support'
    | '/transactions'
    | '/about'
    | '/contact'
    | '/features'
    | '/home'
    | '/how-it-works'
    | '/pricing'
    | '/privacy-policy'
    | '/security'
    | '/terms-of-service'
    | '/api/search'
    | '/docs/$'
    | '/'
    | '/docs'
    | '/admin/audit-trails'
    | '/admin/compliance'
    | '/admin/flagged'
    | '/admin/support'
    | '/audit/overview'
    | '/audit/payments'
    | '/audit/settings'
    | '/audit/statements'
    | '/audit/support'
    | '/dashboard/cards'
    | '/dashboard/overview'
    | '/dashboard/payments'
    | '/dashboard/settings'
    | '/dashboard/statements'
    | '/dashboard/support'
    | '/dashboard/transactions'
    | '/manager/overview'
    | '/manager/payments'
    | '/manager/settings'
    | '/manager/statements'
    | '/manager/support'
    | '/owner/branches'
    | '/owner/overview'
    | '/owner/reports'
    | '/owner/settings'
    | '/owner/staff-performance'
    | '/staff/overview'
    | '/staff/payments'
    | '/staff/settings'
    | '/staff/statements'
    | '/staff/support'
    | '/superadmin/branches'
    | '/superadmin/employees'
    | '/superadmin/overview'
    | '/superadmin/reports'
    | '/superadmin/settings'
    | '/support/overview'
    | '/support/payments'
    | '/support/settings'
    | '/support/statements'
    | '/support/support'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/owner'
    | '/superadmin'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forgot-password'
    | '/reset-password'
    | '/signin'
    | '/signup'
    | '/unauthorized'
    | '/accounts'
    | '/cards'
    | '/dashboard'
    | '/overview'
    | '/reports'
    | '/settings'
    | '/support'
    | '/transactions'
    | '/about'
    | '/contact'
    | '/features'
    | '/home'
    | '/how-it-works'
    | '/pricing'
    | '/privacy-policy'
    | '/security'
    | '/terms-of-service'
    | '/api/search'
    | '/docs/$'
    | '/'
    | '/docs'
    | '/admin/audit-trails'
    | '/admin/compliance'
    | '/admin/flagged'
    | '/admin/support'
    | '/audit/overview'
    | '/audit/payments'
    | '/audit/settings'
    | '/audit/statements'
    | '/audit/support'
    | '/dashboard/cards'
    | '/dashboard/overview'
    | '/dashboard/payments'
    | '/dashboard/settings'
    | '/dashboard/statements'
    | '/dashboard/support'
    | '/dashboard/transactions'
    | '/manager/overview'
    | '/manager/payments'
    | '/manager/settings'
    | '/manager/statements'
    | '/manager/support'
    | '/owner/branches'
    | '/owner/overview'
    | '/owner/reports'
    | '/owner/settings'
    | '/owner/staff-performance'
    | '/staff/overview'
    | '/staff/payments'
    | '/staff/settings'
    | '/staff/statements'
    | '/staff/support'
    | '/superadmin/branches'
    | '/superadmin/employees'
    | '/superadmin/overview'
    | '/superadmin/reports'
    | '/superadmin/settings'
    | '/support/overview'
    | '/support/payments'
    | '/support/settings'
    | '/support/statements'
    | '/support/support'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/owner'
    | '/superadmin'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr'
  id:
    | '__root__'
    | '/(auth)/forgot-password'
    | '/(auth)/reset-password'
    | '/(auth)/signin'
    | '/(auth)/signup'
    | '/(auth)/unauthorized'
    | '/(dashboard)/accounts'
    | '/(dashboard)/cards'
    | '/(dashboard)/dashboard'
    | '/(dashboard)/overview'
    | '/(dashboard)/reports'
    | '/(dashboard)/settings'
    | '/(dashboard)/support'
    | '/(dashboard)/transactions'
    | '/(landing)/about'
    | '/(landing)/contact'
    | '/(landing)/features'
    | '/(landing)/home'
    | '/(landing)/how-it-works'
    | '/(landing)/pricing'
    | '/(landing)/privacy-policy'
    | '/(landing)/security'
    | '/(landing)/terms-of-service'
    | '/api/search'
    | '/docs/$'
    | '/(landing)/'
    | '/docs/'
    | '/(dashboard)/admin/audit-trails'
    | '/(dashboard)/admin/compliance'
    | '/(dashboard)/admin/flagged'
    | '/(dashboard)/admin/support'
    | '/(dashboard)/audit/overview'
    | '/(dashboard)/audit/payments'
    | '/(dashboard)/audit/settings'
    | '/(dashboard)/audit/statements'
    | '/(dashboard)/audit/support'
    | '/(dashboard)/dashboard/cards'
    | '/(dashboard)/dashboard/overview'
    | '/(dashboard)/dashboard/payments'
    | '/(dashboard)/dashboard/settings'
    | '/(dashboard)/dashboard/statements'
    | '/(dashboard)/dashboard/support'
    | '/(dashboard)/dashboard/transactions'
    | '/(dashboard)/manager/overview'
    | '/(dashboard)/manager/payments'
    | '/(dashboard)/manager/settings'
    | '/(dashboard)/manager/statements'
    | '/(dashboard)/manager/support'
    | '/(dashboard)/owner/branches'
    | '/(dashboard)/owner/overview'
    | '/(dashboard)/owner/reports'
    | '/(dashboard)/owner/settings'
    | '/(dashboard)/owner/staff-performance'
    | '/(dashboard)/staff/overview'
    | '/(dashboard)/staff/payments'
    | '/(dashboard)/staff/settings'
    | '/(dashboard)/staff/statements'
    | '/(dashboard)/staff/support'
    | '/(dashboard)/superadmin/branches'
    | '/(dashboard)/superadmin/employees'
    | '/(dashboard)/superadmin/overview'
    | '/(dashboard)/superadmin/reports'
    | '/(dashboard)/superadmin/settings'
    | '/(dashboard)/support/overview'
    | '/(dashboard)/support/payments'
    | '/(dashboard)/support/settings'
    | '/(dashboard)/support/statements'
    | '/(dashboard)/support/support'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/(dashboard)/owner/'
    | '/(dashboard)/superadmin/'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authResetPasswordRoute: typeof authResetPasswordRoute
  authSigninRoute: typeof authSigninRoute
  authSignupRoute: typeof authSignupRoute
  authUnauthorizedRoute: typeof authUnauthorizedRoute
  dashboardAccountsRoute: typeof dashboardAccountsRoute
  dashboardCardsRoute: typeof dashboardCardsRoute
  dashboardDashboardRoute: typeof dashboardDashboardRouteWithChildren
  dashboardOverviewRoute: typeof dashboardOverviewRoute
  dashboardReportsRoute: typeof dashboardReportsRoute
  dashboardSettingsRoute: typeof dashboardSettingsRoute
  dashboardSupportRoute: typeof dashboardSupportRouteWithChildren
  dashboardTransactionsRoute: typeof dashboardTransactionsRoute
  landingAboutRoute: typeof landingAboutRoute
  landingContactRoute: typeof landingContactRoute
  landingFeaturesRoute: typeof landingFeaturesRoute
  landingHomeRoute: typeof landingHomeRoute
  landingHowItWorksRoute: typeof landingHowItWorksRoute
  landingPricingRoute: typeof landingPricingRoute
  landingPrivacyPolicyRoute: typeof landingPrivacyPolicyRoute
  landingSecurityRoute: typeof landingSecurityRoute
  landingTermsOfServiceRoute: typeof landingTermsOfServiceRoute
  ApiSearchRoute: typeof ApiSearchRoute
  DocsSplatRoute: typeof DocsSplatRoute
  landingIndexRoute: typeof landingIndexRoute
  DocsIndexRoute: typeof DocsIndexRoute
  dashboardAdminAuditTrailsRoute: typeof dashboardAdminAuditTrailsRoute
  dashboardAdminComplianceRoute: typeof dashboardAdminComplianceRoute
  dashboardAdminFlaggedRoute: typeof dashboardAdminFlaggedRoute
  dashboardAdminSupportRoute: typeof dashboardAdminSupportRoute
  dashboardAuditOverviewRoute: typeof dashboardAuditOverviewRoute
  dashboardAuditPaymentsRoute: typeof dashboardAuditPaymentsRoute
  dashboardAuditSettingsRoute: typeof dashboardAuditSettingsRoute
  dashboardAuditStatementsRoute: typeof dashboardAuditStatementsRoute
  dashboardAuditSupportRoute: typeof dashboardAuditSupportRoute
  dashboardManagerOverviewRoute: typeof dashboardManagerOverviewRoute
  dashboardManagerPaymentsRoute: typeof dashboardManagerPaymentsRoute
  dashboardManagerSettingsRoute: typeof dashboardManagerSettingsRoute
  dashboardManagerStatementsRoute: typeof dashboardManagerStatementsRoute
  dashboardManagerSupportRoute: typeof dashboardManagerSupportRoute
  dashboardOwnerBranchesRoute: typeof dashboardOwnerBranchesRoute
  dashboardOwnerOverviewRoute: typeof dashboardOwnerOverviewRoute
  dashboardOwnerReportsRoute: typeof dashboardOwnerReportsRoute
  dashboardOwnerSettingsRoute: typeof dashboardOwnerSettingsRoute
  dashboardOwnerStaffPerformanceRoute: typeof dashboardOwnerStaffPerformanceRoute
  dashboardStaffOverviewRoute: typeof dashboardStaffOverviewRoute
  dashboardStaffPaymentsRoute: typeof dashboardStaffPaymentsRoute
  dashboardStaffSettingsRoute: typeof dashboardStaffSettingsRoute
  dashboardStaffStatementsRoute: typeof dashboardStaffStatementsRoute
  dashboardStaffSupportRoute: typeof dashboardStaffSupportRoute
  dashboardSuperadminBranchesRoute: typeof dashboardSuperadminBranchesRoute
  dashboardSuperadminEmployeesRoute: typeof dashboardSuperadminEmployeesRoute
  dashboardSuperadminOverviewRoute: typeof dashboardSuperadminOverviewRoute
  dashboardSuperadminReportsRoute: typeof dashboardSuperadminReportsRoute
  dashboardSuperadminSettingsRoute: typeof dashboardSuperadminSettingsRoute
  DemoApiNamesRoute: typeof DemoApiNamesRoute
  DemoStartApiRequestRoute: typeof DemoStartApiRequestRoute
  DemoStartServerFuncsRoute: typeof DemoStartServerFuncsRoute
  dashboardOwnerIndexRoute: typeof dashboardOwnerIndexRoute
  dashboardSuperadminIndexRoute: typeof dashboardSuperadminIndexRoute
  DemoStartSsrDataOnlyRoute: typeof DemoStartSsrDataOnlyRoute
  DemoStartSsrFullSsrRoute: typeof DemoStartSsrFullSsrRoute
  DemoStartSsrSpaModeRoute: typeof DemoStartSsrSpaModeRoute
  DemoStartSsrIndexRoute: typeof DemoStartSsrIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/docs/': {
      id: '/docs/'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(landing)/': {
      id: '/(landing)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof landingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$': {
      id: '/docs/$'
      path: '/docs/$'
      fullPath: '/docs/$'
      preLoaderRoute: typeof DocsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/search': {
      id: '/api/search'
      path: '/api/search'
      fullPath: '/api/search'
      preLoaderRoute: typeof ApiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(landing)/terms-of-service': {
      id: '/(landing)/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/terms-of-service'
      preLoaderRoute: typeof landingTermsOfServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(landing)/security': {
      id: '/(landing)/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof landingSecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(landing)/privacy-policy': {
      id: '/(landing)/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof landingPrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(landing)/pricing': {
      id: '/(landing)/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof landingPricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(landing)/how-it-works': {
      id: '/(landing)/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof landingHowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(landing)/home': {
      id: '/(landing)/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof landingHomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(landing)/features': {
      id: '/(landing)/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof landingFeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(landing)/contact': {
      id: '/(landing)/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof landingContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(landing)/about': {
      id: '/(landing)/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof landingAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/transactions': {
      id: '/(dashboard)/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof dashboardTransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/support': {
      id: '/(dashboard)/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof dashboardSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/settings': {
      id: '/(dashboard)/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof dashboardSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/reports': {
      id: '/(dashboard)/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof dashboardReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/overview': {
      id: '/(dashboard)/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof dashboardOverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/dashboard': {
      id: '/(dashboard)/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof dashboardDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/cards': {
      id: '/(dashboard)/cards'
      path: '/cards'
      fullPath: '/cards'
      preLoaderRoute: typeof dashboardCardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/accounts': {
      id: '/(dashboard)/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof dashboardAccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/unauthorized': {
      id: '/(auth)/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof authUnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/signup': {
      id: '/(auth)/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof authSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/signin': {
      id: '/(auth)/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof authSigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/reset-password': {
      id: '/(auth)/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof authResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/superadmin/': {
      id: '/(dashboard)/superadmin/'
      path: '/superadmin'
      fullPath: '/superadmin'
      preLoaderRoute: typeof dashboardSuperadminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/owner/': {
      id: '/(dashboard)/owner/'
      path: '/owner'
      fullPath: '/owner'
      preLoaderRoute: typeof dashboardOwnerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/server-funcs': {
      id: '/demo/start/server-funcs'
      path: '/demo/start/server-funcs'
      fullPath: '/demo/start/server-funcs'
      preLoaderRoute: typeof DemoStartServerFuncsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/api-request': {
      id: '/demo/start/api-request'
      path: '/demo/start/api-request'
      fullPath: '/demo/start/api-request'
      preLoaderRoute: typeof DemoStartApiRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/names': {
      id: '/demo/api/names'
      path: '/demo/api/names'
      fullPath: '/demo/api/names'
      preLoaderRoute: typeof DemoApiNamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/support/support': {
      id: '/(dashboard)/support/support'
      path: '/support'
      fullPath: '/support/support'
      preLoaderRoute: typeof dashboardSupportSupportRouteImport
      parentRoute: typeof dashboardSupportRoute
    }
    '/(dashboard)/support/statements': {
      id: '/(dashboard)/support/statements'
      path: '/statements'
      fullPath: '/support/statements'
      preLoaderRoute: typeof dashboardSupportStatementsRouteImport
      parentRoute: typeof dashboardSupportRoute
    }
    '/(dashboard)/support/settings': {
      id: '/(dashboard)/support/settings'
      path: '/settings'
      fullPath: '/support/settings'
      preLoaderRoute: typeof dashboardSupportSettingsRouteImport
      parentRoute: typeof dashboardSupportRoute
    }
    '/(dashboard)/support/payments': {
      id: '/(dashboard)/support/payments'
      path: '/payments'
      fullPath: '/support/payments'
      preLoaderRoute: typeof dashboardSupportPaymentsRouteImport
      parentRoute: typeof dashboardSupportRoute
    }
    '/(dashboard)/support/overview': {
      id: '/(dashboard)/support/overview'
      path: '/overview'
      fullPath: '/support/overview'
      preLoaderRoute: typeof dashboardSupportOverviewRouteImport
      parentRoute: typeof dashboardSupportRoute
    }
    '/(dashboard)/superadmin/settings': {
      id: '/(dashboard)/superadmin/settings'
      path: '/superadmin/settings'
      fullPath: '/superadmin/settings'
      preLoaderRoute: typeof dashboardSuperadminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/superadmin/reports': {
      id: '/(dashboard)/superadmin/reports'
      path: '/superadmin/reports'
      fullPath: '/superadmin/reports'
      preLoaderRoute: typeof dashboardSuperadminReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/superadmin/overview': {
      id: '/(dashboard)/superadmin/overview'
      path: '/superadmin/overview'
      fullPath: '/superadmin/overview'
      preLoaderRoute: typeof dashboardSuperadminOverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/superadmin/employees': {
      id: '/(dashboard)/superadmin/employees'
      path: '/superadmin/employees'
      fullPath: '/superadmin/employees'
      preLoaderRoute: typeof dashboardSuperadminEmployeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/superadmin/branches': {
      id: '/(dashboard)/superadmin/branches'
      path: '/superadmin/branches'
      fullPath: '/superadmin/branches'
      preLoaderRoute: typeof dashboardSuperadminBranchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/staff/support': {
      id: '/(dashboard)/staff/support'
      path: '/staff/support'
      fullPath: '/staff/support'
      preLoaderRoute: typeof dashboardStaffSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/staff/statements': {
      id: '/(dashboard)/staff/statements'
      path: '/staff/statements'
      fullPath: '/staff/statements'
      preLoaderRoute: typeof dashboardStaffStatementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/staff/settings': {
      id: '/(dashboard)/staff/settings'
      path: '/staff/settings'
      fullPath: '/staff/settings'
      preLoaderRoute: typeof dashboardStaffSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/staff/payments': {
      id: '/(dashboard)/staff/payments'
      path: '/staff/payments'
      fullPath: '/staff/payments'
      preLoaderRoute: typeof dashboardStaffPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/staff/overview': {
      id: '/(dashboard)/staff/overview'
      path: '/staff/overview'
      fullPath: '/staff/overview'
      preLoaderRoute: typeof dashboardStaffOverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/owner/staff-performance': {
      id: '/(dashboard)/owner/staff-performance'
      path: '/owner/staff-performance'
      fullPath: '/owner/staff-performance'
      preLoaderRoute: typeof dashboardOwnerStaffPerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/owner/settings': {
      id: '/(dashboard)/owner/settings'
      path: '/owner/settings'
      fullPath: '/owner/settings'
      preLoaderRoute: typeof dashboardOwnerSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/owner/reports': {
      id: '/(dashboard)/owner/reports'
      path: '/owner/reports'
      fullPath: '/owner/reports'
      preLoaderRoute: typeof dashboardOwnerReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/owner/overview': {
      id: '/(dashboard)/owner/overview'
      path: '/owner/overview'
      fullPath: '/owner/overview'
      preLoaderRoute: typeof dashboardOwnerOverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/owner/branches': {
      id: '/(dashboard)/owner/branches'
      path: '/owner/branches'
      fullPath: '/owner/branches'
      preLoaderRoute: typeof dashboardOwnerBranchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/manager/support': {
      id: '/(dashboard)/manager/support'
      path: '/manager/support'
      fullPath: '/manager/support'
      preLoaderRoute: typeof dashboardManagerSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/manager/statements': {
      id: '/(dashboard)/manager/statements'
      path: '/manager/statements'
      fullPath: '/manager/statements'
      preLoaderRoute: typeof dashboardManagerStatementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/manager/settings': {
      id: '/(dashboard)/manager/settings'
      path: '/manager/settings'
      fullPath: '/manager/settings'
      preLoaderRoute: typeof dashboardManagerSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/manager/payments': {
      id: '/(dashboard)/manager/payments'
      path: '/manager/payments'
      fullPath: '/manager/payments'
      preLoaderRoute: typeof dashboardManagerPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/manager/overview': {
      id: '/(dashboard)/manager/overview'
      path: '/manager/overview'
      fullPath: '/manager/overview'
      preLoaderRoute: typeof dashboardManagerOverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/dashboard/transactions': {
      id: '/(dashboard)/dashboard/transactions'
      path: '/transactions'
      fullPath: '/dashboard/transactions'
      preLoaderRoute: typeof dashboardDashboardTransactionsRouteImport
      parentRoute: typeof dashboardDashboardRoute
    }
    '/(dashboard)/dashboard/support': {
      id: '/(dashboard)/dashboard/support'
      path: '/support'
      fullPath: '/dashboard/support'
      preLoaderRoute: typeof dashboardDashboardSupportRouteImport
      parentRoute: typeof dashboardDashboardRoute
    }
    '/(dashboard)/dashboard/statements': {
      id: '/(dashboard)/dashboard/statements'
      path: '/statements'
      fullPath: '/dashboard/statements'
      preLoaderRoute: typeof dashboardDashboardStatementsRouteImport
      parentRoute: typeof dashboardDashboardRoute
    }
    '/(dashboard)/dashboard/settings': {
      id: '/(dashboard)/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof dashboardDashboardSettingsRouteImport
      parentRoute: typeof dashboardDashboardRoute
    }
    '/(dashboard)/dashboard/payments': {
      id: '/(dashboard)/dashboard/payments'
      path: '/payments'
      fullPath: '/dashboard/payments'
      preLoaderRoute: typeof dashboardDashboardPaymentsRouteImport
      parentRoute: typeof dashboardDashboardRoute
    }
    '/(dashboard)/dashboard/overview': {
      id: '/(dashboard)/dashboard/overview'
      path: '/overview'
      fullPath: '/dashboard/overview'
      preLoaderRoute: typeof dashboardDashboardOverviewRouteImport
      parentRoute: typeof dashboardDashboardRoute
    }
    '/(dashboard)/dashboard/cards': {
      id: '/(dashboard)/dashboard/cards'
      path: '/cards'
      fullPath: '/dashboard/cards'
      preLoaderRoute: typeof dashboardDashboardCardsRouteImport
      parentRoute: typeof dashboardDashboardRoute
    }
    '/(dashboard)/audit/support': {
      id: '/(dashboard)/audit/support'
      path: '/audit/support'
      fullPath: '/audit/support'
      preLoaderRoute: typeof dashboardAuditSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/audit/statements': {
      id: '/(dashboard)/audit/statements'
      path: '/audit/statements'
      fullPath: '/audit/statements'
      preLoaderRoute: typeof dashboardAuditStatementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/audit/settings': {
      id: '/(dashboard)/audit/settings'
      path: '/audit/settings'
      fullPath: '/audit/settings'
      preLoaderRoute: typeof dashboardAuditSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/audit/payments': {
      id: '/(dashboard)/audit/payments'
      path: '/audit/payments'
      fullPath: '/audit/payments'
      preLoaderRoute: typeof dashboardAuditPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/audit/overview': {
      id: '/(dashboard)/audit/overview'
      path: '/audit/overview'
      fullPath: '/audit/overview'
      preLoaderRoute: typeof dashboardAuditOverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/admin/support': {
      id: '/(dashboard)/admin/support'
      path: '/admin/support'
      fullPath: '/admin/support'
      preLoaderRoute: typeof dashboardAdminSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/admin/flagged': {
      id: '/(dashboard)/admin/flagged'
      path: '/admin/flagged'
      fullPath: '/admin/flagged'
      preLoaderRoute: typeof dashboardAdminFlaggedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/admin/compliance': {
      id: '/(dashboard)/admin/compliance'
      path: '/admin/compliance'
      fullPath: '/admin/compliance'
      preLoaderRoute: typeof dashboardAdminComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/admin/audit-trails': {
      id: '/(dashboard)/admin/audit-trails'
      path: '/admin/audit-trails'
      fullPath: '/admin/audit-trails'
      preLoaderRoute: typeof dashboardAdminAuditTrailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/': {
      id: '/demo/start/ssr/'
      path: '/demo/start/ssr'
      fullPath: '/demo/start/ssr'
      preLoaderRoute: typeof DemoStartSsrIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/spa-mode': {
      id: '/demo/start/ssr/spa-mode'
      path: '/demo/start/ssr/spa-mode'
      fullPath: '/demo/start/ssr/spa-mode'
      preLoaderRoute: typeof DemoStartSsrSpaModeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/full-ssr': {
      id: '/demo/start/ssr/full-ssr'
      path: '/demo/start/ssr/full-ssr'
      fullPath: '/demo/start/ssr/full-ssr'
      preLoaderRoute: typeof DemoStartSsrFullSsrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/data-only': {
      id: '/demo/start/ssr/data-only'
      path: '/demo/start/ssr/data-only'
      fullPath: '/demo/start/ssr/data-only'
      preLoaderRoute: typeof DemoStartSsrDataOnlyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface dashboardDashboardRouteChildren {
  dashboardDashboardCardsRoute: typeof dashboardDashboardCardsRoute
  dashboardDashboardOverviewRoute: typeof dashboardDashboardOverviewRoute
  dashboardDashboardPaymentsRoute: typeof dashboardDashboardPaymentsRoute
  dashboardDashboardSettingsRoute: typeof dashboardDashboardSettingsRoute
  dashboardDashboardStatementsRoute: typeof dashboardDashboardStatementsRoute
  dashboardDashboardSupportRoute: typeof dashboardDashboardSupportRoute
  dashboardDashboardTransactionsRoute: typeof dashboardDashboardTransactionsRoute
}

const dashboardDashboardRouteChildren: dashboardDashboardRouteChildren = {
  dashboardDashboardCardsRoute: dashboardDashboardCardsRoute,
  dashboardDashboardOverviewRoute: dashboardDashboardOverviewRoute,
  dashboardDashboardPaymentsRoute: dashboardDashboardPaymentsRoute,
  dashboardDashboardSettingsRoute: dashboardDashboardSettingsRoute,
  dashboardDashboardStatementsRoute: dashboardDashboardStatementsRoute,
  dashboardDashboardSupportRoute: dashboardDashboardSupportRoute,
  dashboardDashboardTransactionsRoute: dashboardDashboardTransactionsRoute,
}

const dashboardDashboardRouteWithChildren =
  dashboardDashboardRoute._addFileChildren(dashboardDashboardRouteChildren)

interface dashboardSupportRouteChildren {
  dashboardSupportOverviewRoute: typeof dashboardSupportOverviewRoute
  dashboardSupportPaymentsRoute: typeof dashboardSupportPaymentsRoute
  dashboardSupportSettingsRoute: typeof dashboardSupportSettingsRoute
  dashboardSupportStatementsRoute: typeof dashboardSupportStatementsRoute
  dashboardSupportSupportRoute: typeof dashboardSupportSupportRoute
}

const dashboardSupportRouteChildren: dashboardSupportRouteChildren = {
  dashboardSupportOverviewRoute: dashboardSupportOverviewRoute,
  dashboardSupportPaymentsRoute: dashboardSupportPaymentsRoute,
  dashboardSupportSettingsRoute: dashboardSupportSettingsRoute,
  dashboardSupportStatementsRoute: dashboardSupportStatementsRoute,
  dashboardSupportSupportRoute: dashboardSupportSupportRoute,
}

const dashboardSupportRouteWithChildren =
  dashboardSupportRoute._addFileChildren(dashboardSupportRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  authForgotPasswordRoute: authForgotPasswordRoute,
  authResetPasswordRoute: authResetPasswordRoute,
  authSigninRoute: authSigninRoute,
  authSignupRoute: authSignupRoute,
  authUnauthorizedRoute: authUnauthorizedRoute,
  dashboardAccountsRoute: dashboardAccountsRoute,
  dashboardCardsRoute: dashboardCardsRoute,
  dashboardDashboardRoute: dashboardDashboardRouteWithChildren,
  dashboardOverviewRoute: dashboardOverviewRoute,
  dashboardReportsRoute: dashboardReportsRoute,
  dashboardSettingsRoute: dashboardSettingsRoute,
  dashboardSupportRoute: dashboardSupportRouteWithChildren,
  dashboardTransactionsRoute: dashboardTransactionsRoute,
  landingAboutRoute: landingAboutRoute,
  landingContactRoute: landingContactRoute,
  landingFeaturesRoute: landingFeaturesRoute,
  landingHomeRoute: landingHomeRoute,
  landingHowItWorksRoute: landingHowItWorksRoute,
  landingPricingRoute: landingPricingRoute,
  landingPrivacyPolicyRoute: landingPrivacyPolicyRoute,
  landingSecurityRoute: landingSecurityRoute,
  landingTermsOfServiceRoute: landingTermsOfServiceRoute,
  ApiSearchRoute: ApiSearchRoute,
  DocsSplatRoute: DocsSplatRoute,
  landingIndexRoute: landingIndexRoute,
  DocsIndexRoute: DocsIndexRoute,
  dashboardAdminAuditTrailsRoute: dashboardAdminAuditTrailsRoute,
  dashboardAdminComplianceRoute: dashboardAdminComplianceRoute,
  dashboardAdminFlaggedRoute: dashboardAdminFlaggedRoute,
  dashboardAdminSupportRoute: dashboardAdminSupportRoute,
  dashboardAuditOverviewRoute: dashboardAuditOverviewRoute,
  dashboardAuditPaymentsRoute: dashboardAuditPaymentsRoute,
  dashboardAuditSettingsRoute: dashboardAuditSettingsRoute,
  dashboardAuditStatementsRoute: dashboardAuditStatementsRoute,
  dashboardAuditSupportRoute: dashboardAuditSupportRoute,
  dashboardManagerOverviewRoute: dashboardManagerOverviewRoute,
  dashboardManagerPaymentsRoute: dashboardManagerPaymentsRoute,
  dashboardManagerSettingsRoute: dashboardManagerSettingsRoute,
  dashboardManagerStatementsRoute: dashboardManagerStatementsRoute,
  dashboardManagerSupportRoute: dashboardManagerSupportRoute,
  dashboardOwnerBranchesRoute: dashboardOwnerBranchesRoute,
  dashboardOwnerOverviewRoute: dashboardOwnerOverviewRoute,
  dashboardOwnerReportsRoute: dashboardOwnerReportsRoute,
  dashboardOwnerSettingsRoute: dashboardOwnerSettingsRoute,
  dashboardOwnerStaffPerformanceRoute: dashboardOwnerStaffPerformanceRoute,
  dashboardStaffOverviewRoute: dashboardStaffOverviewRoute,
  dashboardStaffPaymentsRoute: dashboardStaffPaymentsRoute,
  dashboardStaffSettingsRoute: dashboardStaffSettingsRoute,
  dashboardStaffStatementsRoute: dashboardStaffStatementsRoute,
  dashboardStaffSupportRoute: dashboardStaffSupportRoute,
  dashboardSuperadminBranchesRoute: dashboardSuperadminBranchesRoute,
  dashboardSuperadminEmployeesRoute: dashboardSuperadminEmployeesRoute,
  dashboardSuperadminOverviewRoute: dashboardSuperadminOverviewRoute,
  dashboardSuperadminReportsRoute: dashboardSuperadminReportsRoute,
  dashboardSuperadminSettingsRoute: dashboardSuperadminSettingsRoute,
  DemoApiNamesRoute: DemoApiNamesRoute,
  DemoStartApiRequestRoute: DemoStartApiRequestRoute,
  DemoStartServerFuncsRoute: DemoStartServerFuncsRoute,
  dashboardOwnerIndexRoute: dashboardOwnerIndexRoute,
  dashboardSuperadminIndexRoute: dashboardSuperadminIndexRoute,
  DemoStartSsrDataOnlyRoute: DemoStartSsrDataOnlyRoute,
  DemoStartSsrFullSsrRoute: DemoStartSsrFullSsrRoute,
  DemoStartSsrSpaModeRoute: DemoStartSsrSpaModeRoute,
  DemoStartSsrIndexRoute: DemoStartSsrIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
