/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DocsIndexRouteImport } from './routes/docs/index'
import { Route as landingIndexRouteImport } from './routes/(landing)/index'
import { Route as DocsSplatRouteImport } from './routes/docs/$'
import { Route as ApiSearchRouteImport } from './routes/api/search'
import { Route as landingTermsOfServiceRouteImport } from './routes/(landing)/terms-of-service'
import { Route as landingSecurityRouteImport } from './routes/(landing)/security'
import { Route as landingPrivacyPolicyRouteImport } from './routes/(landing)/privacy-policy'
import { Route as landingHowItWorksRouteImport } from './routes/(landing)/how-it-works'
import { Route as landingFeaturesRouteImport } from './routes/(landing)/features'
import { Route as landingContactRouteImport } from './routes/(landing)/contact'
import { Route as landingAboutRouteImport } from './routes/(landing)/about'
import { Route as authVerifyRouteImport } from './routes/(auth)/verify'
import { Route as authUnauthorizedRouteImport } from './routes/(auth)/unauthorized'
import { Route as authSignupRouteImport } from './routes/(auth)/signup'
import { Route as authSigninRouteImport } from './routes/(auth)/signin'
import { Route as authResetPasswordRouteImport } from './routes/(auth)/reset-password'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as dashboardDashboardIndexRouteImport } from './routes/(dashboard)/dashboard/index'
import { Route as dashboardSupportUsersRouteImport } from './routes/(dashboard)/support/users'
import { Route as dashboardSupportTicketsRouteImport } from './routes/(dashboard)/support/tickets'
import { Route as dashboardSupportSupportRouteImport } from './routes/(dashboard)/support/support'
import { Route as dashboardSupportStatementsRouteImport } from './routes/(dashboard)/support/statements'
import { Route as dashboardSupportSettingsRouteImport } from './routes/(dashboard)/support/settings'
import { Route as dashboardSupportPaymentsRouteImport } from './routes/(dashboard)/support/payments'
import { Route as dashboardSupportOverviewRouteImport } from './routes/(dashboard)/support/overview'
import { Route as dashboardSupportKnowledgeRouteImport } from './routes/(dashboard)/support/knowledge'
import { Route as dashboardSupportChatRouteImport } from './routes/(dashboard)/support/chat'
import { Route as dashboardMerchantWebhooksRouteImport } from './routes/(dashboard)/merchant/webhooks'
import { Route as dashboardMerchantSupportRouteImport } from './routes/(dashboard)/merchant/support'
import { Route as dashboardMerchantSettlementsRouteImport } from './routes/(dashboard)/merchant/settlements'
import { Route as dashboardMerchantSettingsRouteImport } from './routes/(dashboard)/merchant/settings'
import { Route as dashboardMerchantPaymentsRouteImport } from './routes/(dashboard)/merchant/payments'
import { Route as dashboardMerchantOverviewRouteImport } from './routes/(dashboard)/merchant/overview'
import { Route as dashboardMerchantApiKeysRouteImport } from './routes/(dashboard)/merchant/api-keys'
import { Route as dashboardMerchantAnalyticsRouteImport } from './routes/(dashboard)/merchant/analytics'
import { Route as dashboardDashboardTopUpRouteImport } from './routes/(dashboard)/dashboard/top-up'
import { Route as dashboardDashboardSupportRouteImport } from './routes/(dashboard)/dashboard/support'
import { Route as dashboardDashboardSettingsRouteImport } from './routes/(dashboard)/dashboard/settings'
import { Route as dashboardDashboardSendMoneyRouteImport } from './routes/(dashboard)/dashboard/send-money'
import { Route as dashboardDashboardRequestMoneyRouteImport } from './routes/(dashboard)/dashboard/request-money'
import { Route as dashboardDashboardReportsRouteImport } from './routes/(dashboard)/dashboard/reports'
import { Route as dashboardDashboardOverviewRouteImport } from './routes/(dashboard)/dashboard/overview'
import { Route as dashboardDashboardCardsRouteImport } from './routes/(dashboard)/dashboard/cards'
import { Route as dashboardDashboardBillsRouteImport } from './routes/(dashboard)/dashboard/bills'
import { Route as dashboardDashboardAnalyticsRouteImport } from './routes/(dashboard)/dashboard/analytics'
import { Route as dashboardDashboardAccountsRouteImport } from './routes/(dashboard)/dashboard/accounts'
import { Route as dashboardAdminUsersRouteImport } from './routes/(dashboard)/admin/users'
import { Route as dashboardAdminTransactionsRouteImport } from './routes/(dashboard)/admin/transactions'
import { Route as dashboardAdminSupportRouteImport } from './routes/(dashboard)/admin/support'
import { Route as dashboardAdminSettingsRouteImport } from './routes/(dashboard)/admin/settings'
import { Route as dashboardAdminReportsRouteImport } from './routes/(dashboard)/admin/reports'
import { Route as dashboardAdminOverviewRouteImport } from './routes/(dashboard)/admin/overview'
import { Route as dashboardAdminComplianceRouteImport } from './routes/(dashboard)/admin/compliance'
import { Route as dashboardAdminAuditTrailsRouteImport } from './routes/(dashboard)/admin/audit-trails'
import { Route as dashboardDashboardTransactionsIndexRouteImport } from './routes/(dashboard)/dashboard/transactions/index'
import { Route as dashboardDashboardTransactionsIdRouteImport } from './routes/(dashboard)/dashboard/transactions/$id'

const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/docs/',
  path: '/docs/',
  getParentRoute: () => rootRouteImport,
} as any)
const landingIndexRoute = landingIndexRouteImport.update({
  id: '/(landing)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsSplatRoute = DocsSplatRouteImport.update({
  id: '/docs/$',
  path: '/docs/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSearchRoute = ApiSearchRouteImport.update({
  id: '/api/search',
  path: '/api/search',
  getParentRoute: () => rootRouteImport,
} as any)
const landingTermsOfServiceRoute = landingTermsOfServiceRouteImport.update({
  id: '/(landing)/terms-of-service',
  path: '/terms-of-service',
  getParentRoute: () => rootRouteImport,
} as any)
const landingSecurityRoute = landingSecurityRouteImport.update({
  id: '/(landing)/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const landingPrivacyPolicyRoute = landingPrivacyPolicyRouteImport.update({
  id: '/(landing)/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const landingHowItWorksRoute = landingHowItWorksRouteImport.update({
  id: '/(landing)/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const landingFeaturesRoute = landingFeaturesRouteImport.update({
  id: '/(landing)/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const landingContactRoute = landingContactRouteImport.update({
  id: '/(landing)/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const landingAboutRoute = landingAboutRouteImport.update({
  id: '/(landing)/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const authVerifyRoute = authVerifyRouteImport.update({
  id: '/(auth)/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const authUnauthorizedRoute = authUnauthorizedRouteImport.update({
  id: '/(auth)/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignupRoute = authSignupRouteImport.update({
  id: '/(auth)/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const authSigninRoute = authSigninRouteImport.update({
  id: '/(auth)/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const authResetPasswordRoute = authResetPasswordRouteImport.update({
  id: '/(auth)/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboardDashboardIndexRoute = dashboardDashboardIndexRouteImport.update({
  id: '/(dashboard)/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboardSupportUsersRoute = dashboardSupportUsersRouteImport.update({
  id: '/(dashboard)/support/users',
  path: '/support/users',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboardSupportTicketsRoute = dashboardSupportTicketsRouteImport.update({
  id: '/(dashboard)/support/tickets',
  path: '/support/tickets',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboardSupportSupportRoute = dashboardSupportSupportRouteImport.update({
  id: '/(dashboard)/support/support',
  path: '/support/support',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboardSupportStatementsRoute =
  dashboardSupportStatementsRouteImport.update({
    id: '/(dashboard)/support/statements',
    path: '/support/statements',
    getParentRoute: () => rootRouteImport,
  } as any)
const dashboardSupportSettingsRoute =
  dashboardSupportSettingsRouteImport.update({
    id: '/(dashboard)/support/settings',
    path: '/support/settings',
    getParentRoute: () => rootRouteImport,
  } as any)
const dashboardSupportPaymentsRoute =
  dashboardSupportPaymentsRouteImport.update({
    id: '/(dashboard)/support/payments',
    path: '/support/payments',
    getParentRoute: () => rootRouteImport,
  } as any)
const dashboardSupportOverviewRoute =
  dashboardSupportOverviewRouteImport.update({
    id: '/(dashboard)/support/overview',
    path: '/support/overview',
    getParentRoute: () => rootRouteImport,
  } as any)
const dashboardSupportKnowledgeRoute =
  dashboardSupportKnowledgeRouteImport.update({
    id: '/(dashboard)/support/knowledge',
    path: '/support/knowledge',
    getParentRoute: () => rootRouteImport,
  } as any)
const dashboardSupportChatRoute = dashboardSupportChatRouteImport.update({
  id: '/(dashboard)/support/chat',
  path: '/support/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboardMerchantWebhooksRoute =
  dashboardMerchantWebhooksRouteImport.update({
    id: '/(dashboard)/merchant/webhooks',
    path: '/merchant/webhooks',
    getParentRoute: () => rootRouteImport,
  } as any)
const dashboardMerchantSupportRoute =
  dashboardMerchantSupportRouteImport.update({
    id: '/(dashboard)/merchant/support',
    path: '/merchant/support',
    getParentRoute: () => rootRouteImport,
  } as any)
const dashboardMerchantSettlementsRoute =
  dashboardMerchantSettlementsRouteImport.update({
    id: '/(dashboard)/merchant/settlements',
    path: '/merchant/settlements',
    getParentRoute: () => rootRouteImport,
  } as any)
const dashboardMerchantSettingsRoute =
  dashboardMerchantSettingsRouteImport.update({
    id: '/(dashboard)/merchant/settings',
    path: '/merchant/settings',
    getParentRoute: () => rootRouteImport,
  } as any)
const dashboardMerchantPaymentsRoute =
  dashboardMerchantPaymentsRouteImport.update({
    id: '/(dashboard)/merchant/payments',
    path: '/merchant/payments',
    getParentRoute: () => rootRouteImport,
  } as any)
const dashboardMerchantOverviewRoute =
  dashboardMerchantOverviewRouteImport.update({
    id: '/(dashboard)/merchant/overview',
    path: '/merchant/overview',
    getParentRoute: () => rootRouteImport,
  } as any)
const dashboardMerchantApiKeysRoute =
  dashboardMerchantApiKeysRouteImport.update({
    id: '/(dashboard)/merchant/api-keys',
    path: '/merchant/api-keys',
    getParentRoute: () => rootRouteImport,
  } as any)
const dashboardMerchantAnalyticsRoute =
  dashboardMerchantAnalyticsRouteImport.update({
    id: '/(dashboard)/merchant/analytics',
    path: '/merchant/analytics',
    getParentRoute: () => rootRouteImport,
  } as any)
const dashboardDashboardTopUpRoute = dashboardDashboardTopUpRouteImport.update({
  id: '/(dashboard)/dashboard/top-up',
  path: '/dashboard/top-up',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboardDashboardSupportRoute =
  dashboardDashboardSupportRouteImport.update({
    id: '/(dashboard)/dashboard/support',
    path: '/dashboard/support',
    getParentRoute: () => rootRouteImport,
  } as any)
const dashboardDashboardSettingsRoute =
  dashboardDashboardSettingsRouteImport.update({
    id: '/(dashboard)/dashboard/settings',
    path: '/dashboard/settings',
    getParentRoute: () => rootRouteImport,
  } as any)
const dashboardDashboardSendMoneyRoute =
  dashboardDashboardSendMoneyRouteImport.update({
    id: '/(dashboard)/dashboard/send-money',
    path: '/dashboard/send-money',
    getParentRoute: () => rootRouteImport,
  } as any)
const dashboardDashboardRequestMoneyRoute =
  dashboardDashboardRequestMoneyRouteImport.update({
    id: '/(dashboard)/dashboard/request-money',
    path: '/dashboard/request-money',
    getParentRoute: () => rootRouteImport,
  } as any)
const dashboardDashboardReportsRoute =
  dashboardDashboardReportsRouteImport.update({
    id: '/(dashboard)/dashboard/reports',
    path: '/dashboard/reports',
    getParentRoute: () => rootRouteImport,
  } as any)
const dashboardDashboardOverviewRoute =
  dashboardDashboardOverviewRouteImport.update({
    id: '/(dashboard)/dashboard/overview',
    path: '/dashboard/overview',
    getParentRoute: () => rootRouteImport,
  } as any)
const dashboardDashboardCardsRoute = dashboardDashboardCardsRouteImport.update({
  id: '/(dashboard)/dashboard/cards',
  path: '/dashboard/cards',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboardDashboardBillsRoute = dashboardDashboardBillsRouteImport.update({
  id: '/(dashboard)/dashboard/bills',
  path: '/dashboard/bills',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboardDashboardAnalyticsRoute =
  dashboardDashboardAnalyticsRouteImport.update({
    id: '/(dashboard)/dashboard/analytics',
    path: '/dashboard/analytics',
    getParentRoute: () => rootRouteImport,
  } as any)
const dashboardDashboardAccountsRoute =
  dashboardDashboardAccountsRouteImport.update({
    id: '/(dashboard)/dashboard/accounts',
    path: '/dashboard/accounts',
    getParentRoute: () => rootRouteImport,
  } as any)
const dashboardAdminUsersRoute = dashboardAdminUsersRouteImport.update({
  id: '/(dashboard)/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboardAdminTransactionsRoute =
  dashboardAdminTransactionsRouteImport.update({
    id: '/(dashboard)/admin/transactions',
    path: '/admin/transactions',
    getParentRoute: () => rootRouteImport,
  } as any)
const dashboardAdminSupportRoute = dashboardAdminSupportRouteImport.update({
  id: '/(dashboard)/admin/support',
  path: '/admin/support',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboardAdminSettingsRoute = dashboardAdminSettingsRouteImport.update({
  id: '/(dashboard)/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboardAdminReportsRoute = dashboardAdminReportsRouteImport.update({
  id: '/(dashboard)/admin/reports',
  path: '/admin/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboardAdminOverviewRoute = dashboardAdminOverviewRouteImport.update({
  id: '/(dashboard)/admin/overview',
  path: '/admin/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboardAdminComplianceRoute =
  dashboardAdminComplianceRouteImport.update({
    id: '/(dashboard)/admin/compliance',
    path: '/admin/compliance',
    getParentRoute: () => rootRouteImport,
  } as any)
const dashboardAdminAuditTrailsRoute =
  dashboardAdminAuditTrailsRouteImport.update({
    id: '/(dashboard)/admin/audit-trails',
    path: '/admin/audit-trails',
    getParentRoute: () => rootRouteImport,
  } as any)
const dashboardDashboardTransactionsIndexRoute =
  dashboardDashboardTransactionsIndexRouteImport.update({
    id: '/(dashboard)/dashboard/transactions/',
    path: '/dashboard/transactions/',
    getParentRoute: () => rootRouteImport,
  } as any)
const dashboardDashboardTransactionsIdRoute =
  dashboardDashboardTransactionsIdRouteImport.update({
    id: '/(dashboard)/dashboard/transactions/$id',
    path: '/dashboard/transactions/$id',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/forgot-password': typeof authForgotPasswordRoute
  '/reset-password': typeof authResetPasswordRoute
  '/signin': typeof authSigninRoute
  '/signup': typeof authSignupRoute
  '/unauthorized': typeof authUnauthorizedRoute
  '/verify': typeof authVerifyRoute
  '/about': typeof landingAboutRoute
  '/contact': typeof landingContactRoute
  '/features': typeof landingFeaturesRoute
  '/how-it-works': typeof landingHowItWorksRoute
  '/privacy-policy': typeof landingPrivacyPolicyRoute
  '/security': typeof landingSecurityRoute
  '/terms-of-service': typeof landingTermsOfServiceRoute
  '/api/search': typeof ApiSearchRoute
  '/docs/$': typeof DocsSplatRoute
  '/': typeof landingIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/admin/audit-trails': typeof dashboardAdminAuditTrailsRoute
  '/admin/compliance': typeof dashboardAdminComplianceRoute
  '/admin/overview': typeof dashboardAdminOverviewRoute
  '/admin/reports': typeof dashboardAdminReportsRoute
  '/admin/settings': typeof dashboardAdminSettingsRoute
  '/admin/support': typeof dashboardAdminSupportRoute
  '/admin/transactions': typeof dashboardAdminTransactionsRoute
  '/admin/users': typeof dashboardAdminUsersRoute
  '/dashboard/accounts': typeof dashboardDashboardAccountsRoute
  '/dashboard/analytics': typeof dashboardDashboardAnalyticsRoute
  '/dashboard/bills': typeof dashboardDashboardBillsRoute
  '/dashboard/cards': typeof dashboardDashboardCardsRoute
  '/dashboard/overview': typeof dashboardDashboardOverviewRoute
  '/dashboard/reports': typeof dashboardDashboardReportsRoute
  '/dashboard/request-money': typeof dashboardDashboardRequestMoneyRoute
  '/dashboard/send-money': typeof dashboardDashboardSendMoneyRoute
  '/dashboard/settings': typeof dashboardDashboardSettingsRoute
  '/dashboard/support': typeof dashboardDashboardSupportRoute
  '/dashboard/top-up': typeof dashboardDashboardTopUpRoute
  '/merchant/analytics': typeof dashboardMerchantAnalyticsRoute
  '/merchant/api-keys': typeof dashboardMerchantApiKeysRoute
  '/merchant/overview': typeof dashboardMerchantOverviewRoute
  '/merchant/payments': typeof dashboardMerchantPaymentsRoute
  '/merchant/settings': typeof dashboardMerchantSettingsRoute
  '/merchant/settlements': typeof dashboardMerchantSettlementsRoute
  '/merchant/support': typeof dashboardMerchantSupportRoute
  '/merchant/webhooks': typeof dashboardMerchantWebhooksRoute
  '/support/chat': typeof dashboardSupportChatRoute
  '/support/knowledge': typeof dashboardSupportKnowledgeRoute
  '/support/overview': typeof dashboardSupportOverviewRoute
  '/support/payments': typeof dashboardSupportPaymentsRoute
  '/support/settings': typeof dashboardSupportSettingsRoute
  '/support/statements': typeof dashboardSupportStatementsRoute
  '/support/support': typeof dashboardSupportSupportRoute
  '/support/tickets': typeof dashboardSupportTicketsRoute
  '/support/users': typeof dashboardSupportUsersRoute
  '/dashboard/': typeof dashboardDashboardIndexRoute
  '/dashboard/transactions/$id': typeof dashboardDashboardTransactionsIdRoute
  '/dashboard/transactions/': typeof dashboardDashboardTransactionsIndexRoute
}
export interface FileRoutesByTo {
  '/forgot-password': typeof authForgotPasswordRoute
  '/reset-password': typeof authResetPasswordRoute
  '/signin': typeof authSigninRoute
  '/signup': typeof authSignupRoute
  '/unauthorized': typeof authUnauthorizedRoute
  '/verify': typeof authVerifyRoute
  '/about': typeof landingAboutRoute
  '/contact': typeof landingContactRoute
  '/features': typeof landingFeaturesRoute
  '/how-it-works': typeof landingHowItWorksRoute
  '/privacy-policy': typeof landingPrivacyPolicyRoute
  '/security': typeof landingSecurityRoute
  '/terms-of-service': typeof landingTermsOfServiceRoute
  '/api/search': typeof ApiSearchRoute
  '/docs/$': typeof DocsSplatRoute
  '/': typeof landingIndexRoute
  '/docs': typeof DocsIndexRoute
  '/admin/audit-trails': typeof dashboardAdminAuditTrailsRoute
  '/admin/compliance': typeof dashboardAdminComplianceRoute
  '/admin/overview': typeof dashboardAdminOverviewRoute
  '/admin/reports': typeof dashboardAdminReportsRoute
  '/admin/settings': typeof dashboardAdminSettingsRoute
  '/admin/support': typeof dashboardAdminSupportRoute
  '/admin/transactions': typeof dashboardAdminTransactionsRoute
  '/admin/users': typeof dashboardAdminUsersRoute
  '/dashboard/accounts': typeof dashboardDashboardAccountsRoute
  '/dashboard/analytics': typeof dashboardDashboardAnalyticsRoute
  '/dashboard/bills': typeof dashboardDashboardBillsRoute
  '/dashboard/cards': typeof dashboardDashboardCardsRoute
  '/dashboard/overview': typeof dashboardDashboardOverviewRoute
  '/dashboard/reports': typeof dashboardDashboardReportsRoute
  '/dashboard/request-money': typeof dashboardDashboardRequestMoneyRoute
  '/dashboard/send-money': typeof dashboardDashboardSendMoneyRoute
  '/dashboard/settings': typeof dashboardDashboardSettingsRoute
  '/dashboard/support': typeof dashboardDashboardSupportRoute
  '/dashboard/top-up': typeof dashboardDashboardTopUpRoute
  '/merchant/analytics': typeof dashboardMerchantAnalyticsRoute
  '/merchant/api-keys': typeof dashboardMerchantApiKeysRoute
  '/merchant/overview': typeof dashboardMerchantOverviewRoute
  '/merchant/payments': typeof dashboardMerchantPaymentsRoute
  '/merchant/settings': typeof dashboardMerchantSettingsRoute
  '/merchant/settlements': typeof dashboardMerchantSettlementsRoute
  '/merchant/support': typeof dashboardMerchantSupportRoute
  '/merchant/webhooks': typeof dashboardMerchantWebhooksRoute
  '/support/chat': typeof dashboardSupportChatRoute
  '/support/knowledge': typeof dashboardSupportKnowledgeRoute
  '/support/overview': typeof dashboardSupportOverviewRoute
  '/support/payments': typeof dashboardSupportPaymentsRoute
  '/support/settings': typeof dashboardSupportSettingsRoute
  '/support/statements': typeof dashboardSupportStatementsRoute
  '/support/support': typeof dashboardSupportSupportRoute
  '/support/tickets': typeof dashboardSupportTicketsRoute
  '/support/users': typeof dashboardSupportUsersRoute
  '/dashboard': typeof dashboardDashboardIndexRoute
  '/dashboard/transactions/$id': typeof dashboardDashboardTransactionsIdRoute
  '/dashboard/transactions': typeof dashboardDashboardTransactionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/reset-password': typeof authResetPasswordRoute
  '/(auth)/signin': typeof authSigninRoute
  '/(auth)/signup': typeof authSignupRoute
  '/(auth)/unauthorized': typeof authUnauthorizedRoute
  '/(auth)/verify': typeof authVerifyRoute
  '/(landing)/about': typeof landingAboutRoute
  '/(landing)/contact': typeof landingContactRoute
  '/(landing)/features': typeof landingFeaturesRoute
  '/(landing)/how-it-works': typeof landingHowItWorksRoute
  '/(landing)/privacy-policy': typeof landingPrivacyPolicyRoute
  '/(landing)/security': typeof landingSecurityRoute
  '/(landing)/terms-of-service': typeof landingTermsOfServiceRoute
  '/api/search': typeof ApiSearchRoute
  '/docs/$': typeof DocsSplatRoute
  '/(landing)/': typeof landingIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/(dashboard)/admin/audit-trails': typeof dashboardAdminAuditTrailsRoute
  '/(dashboard)/admin/compliance': typeof dashboardAdminComplianceRoute
  '/(dashboard)/admin/overview': typeof dashboardAdminOverviewRoute
  '/(dashboard)/admin/reports': typeof dashboardAdminReportsRoute
  '/(dashboard)/admin/settings': typeof dashboardAdminSettingsRoute
  '/(dashboard)/admin/support': typeof dashboardAdminSupportRoute
  '/(dashboard)/admin/transactions': typeof dashboardAdminTransactionsRoute
  '/(dashboard)/admin/users': typeof dashboardAdminUsersRoute
  '/(dashboard)/dashboard/accounts': typeof dashboardDashboardAccountsRoute
  '/(dashboard)/dashboard/analytics': typeof dashboardDashboardAnalyticsRoute
  '/(dashboard)/dashboard/bills': typeof dashboardDashboardBillsRoute
  '/(dashboard)/dashboard/cards': typeof dashboardDashboardCardsRoute
  '/(dashboard)/dashboard/overview': typeof dashboardDashboardOverviewRoute
  '/(dashboard)/dashboard/reports': typeof dashboardDashboardReportsRoute
  '/(dashboard)/dashboard/request-money': typeof dashboardDashboardRequestMoneyRoute
  '/(dashboard)/dashboard/send-money': typeof dashboardDashboardSendMoneyRoute
  '/(dashboard)/dashboard/settings': typeof dashboardDashboardSettingsRoute
  '/(dashboard)/dashboard/support': typeof dashboardDashboardSupportRoute
  '/(dashboard)/dashboard/top-up': typeof dashboardDashboardTopUpRoute
  '/(dashboard)/merchant/analytics': typeof dashboardMerchantAnalyticsRoute
  '/(dashboard)/merchant/api-keys': typeof dashboardMerchantApiKeysRoute
  '/(dashboard)/merchant/overview': typeof dashboardMerchantOverviewRoute
  '/(dashboard)/merchant/payments': typeof dashboardMerchantPaymentsRoute
  '/(dashboard)/merchant/settings': typeof dashboardMerchantSettingsRoute
  '/(dashboard)/merchant/settlements': typeof dashboardMerchantSettlementsRoute
  '/(dashboard)/merchant/support': typeof dashboardMerchantSupportRoute
  '/(dashboard)/merchant/webhooks': typeof dashboardMerchantWebhooksRoute
  '/(dashboard)/support/chat': typeof dashboardSupportChatRoute
  '/(dashboard)/support/knowledge': typeof dashboardSupportKnowledgeRoute
  '/(dashboard)/support/overview': typeof dashboardSupportOverviewRoute
  '/(dashboard)/support/payments': typeof dashboardSupportPaymentsRoute
  '/(dashboard)/support/settings': typeof dashboardSupportSettingsRoute
  '/(dashboard)/support/statements': typeof dashboardSupportStatementsRoute
  '/(dashboard)/support/support': typeof dashboardSupportSupportRoute
  '/(dashboard)/support/tickets': typeof dashboardSupportTicketsRoute
  '/(dashboard)/support/users': typeof dashboardSupportUsersRoute
  '/(dashboard)/dashboard/': typeof dashboardDashboardIndexRoute
  '/(dashboard)/dashboard/transactions/$id': typeof dashboardDashboardTransactionsIdRoute
  '/(dashboard)/dashboard/transactions/': typeof dashboardDashboardTransactionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/forgot-password'
    | '/reset-password'
    | '/signin'
    | '/signup'
    | '/unauthorized'
    | '/verify'
    | '/about'
    | '/contact'
    | '/features'
    | '/how-it-works'
    | '/privacy-policy'
    | '/security'
    | '/terms-of-service'
    | '/api/search'
    | '/docs/$'
    | '/'
    | '/docs/'
    | '/admin/audit-trails'
    | '/admin/compliance'
    | '/admin/overview'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/support'
    | '/admin/transactions'
    | '/admin/users'
    | '/dashboard/accounts'
    | '/dashboard/analytics'
    | '/dashboard/bills'
    | '/dashboard/cards'
    | '/dashboard/overview'
    | '/dashboard/reports'
    | '/dashboard/request-money'
    | '/dashboard/send-money'
    | '/dashboard/settings'
    | '/dashboard/support'
    | '/dashboard/top-up'
    | '/merchant/analytics'
    | '/merchant/api-keys'
    | '/merchant/overview'
    | '/merchant/payments'
    | '/merchant/settings'
    | '/merchant/settlements'
    | '/merchant/support'
    | '/merchant/webhooks'
    | '/support/chat'
    | '/support/knowledge'
    | '/support/overview'
    | '/support/payments'
    | '/support/settings'
    | '/support/statements'
    | '/support/support'
    | '/support/tickets'
    | '/support/users'
    | '/dashboard/'
    | '/dashboard/transactions/$id'
    | '/dashboard/transactions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forgot-password'
    | '/reset-password'
    | '/signin'
    | '/signup'
    | '/unauthorized'
    | '/verify'
    | '/about'
    | '/contact'
    | '/features'
    | '/how-it-works'
    | '/privacy-policy'
    | '/security'
    | '/terms-of-service'
    | '/api/search'
    | '/docs/$'
    | '/'
    | '/docs'
    | '/admin/audit-trails'
    | '/admin/compliance'
    | '/admin/overview'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/support'
    | '/admin/transactions'
    | '/admin/users'
    | '/dashboard/accounts'
    | '/dashboard/analytics'
    | '/dashboard/bills'
    | '/dashboard/cards'
    | '/dashboard/overview'
    | '/dashboard/reports'
    | '/dashboard/request-money'
    | '/dashboard/send-money'
    | '/dashboard/settings'
    | '/dashboard/support'
    | '/dashboard/top-up'
    | '/merchant/analytics'
    | '/merchant/api-keys'
    | '/merchant/overview'
    | '/merchant/payments'
    | '/merchant/settings'
    | '/merchant/settlements'
    | '/merchant/support'
    | '/merchant/webhooks'
    | '/support/chat'
    | '/support/knowledge'
    | '/support/overview'
    | '/support/payments'
    | '/support/settings'
    | '/support/statements'
    | '/support/support'
    | '/support/tickets'
    | '/support/users'
    | '/dashboard'
    | '/dashboard/transactions/$id'
    | '/dashboard/transactions'
  id:
    | '__root__'
    | '/(auth)/forgot-password'
    | '/(auth)/reset-password'
    | '/(auth)/signin'
    | '/(auth)/signup'
    | '/(auth)/unauthorized'
    | '/(auth)/verify'
    | '/(landing)/about'
    | '/(landing)/contact'
    | '/(landing)/features'
    | '/(landing)/how-it-works'
    | '/(landing)/privacy-policy'
    | '/(landing)/security'
    | '/(landing)/terms-of-service'
    | '/api/search'
    | '/docs/$'
    | '/(landing)/'
    | '/docs/'
    | '/(dashboard)/admin/audit-trails'
    | '/(dashboard)/admin/compliance'
    | '/(dashboard)/admin/overview'
    | '/(dashboard)/admin/reports'
    | '/(dashboard)/admin/settings'
    | '/(dashboard)/admin/support'
    | '/(dashboard)/admin/transactions'
    | '/(dashboard)/admin/users'
    | '/(dashboard)/dashboard/accounts'
    | '/(dashboard)/dashboard/analytics'
    | '/(dashboard)/dashboard/bills'
    | '/(dashboard)/dashboard/cards'
    | '/(dashboard)/dashboard/overview'
    | '/(dashboard)/dashboard/reports'
    | '/(dashboard)/dashboard/request-money'
    | '/(dashboard)/dashboard/send-money'
    | '/(dashboard)/dashboard/settings'
    | '/(dashboard)/dashboard/support'
    | '/(dashboard)/dashboard/top-up'
    | '/(dashboard)/merchant/analytics'
    | '/(dashboard)/merchant/api-keys'
    | '/(dashboard)/merchant/overview'
    | '/(dashboard)/merchant/payments'
    | '/(dashboard)/merchant/settings'
    | '/(dashboard)/merchant/settlements'
    | '/(dashboard)/merchant/support'
    | '/(dashboard)/merchant/webhooks'
    | '/(dashboard)/support/chat'
    | '/(dashboard)/support/knowledge'
    | '/(dashboard)/support/overview'
    | '/(dashboard)/support/payments'
    | '/(dashboard)/support/settings'
    | '/(dashboard)/support/statements'
    | '/(dashboard)/support/support'
    | '/(dashboard)/support/tickets'
    | '/(dashboard)/support/users'
    | '/(dashboard)/dashboard/'
    | '/(dashboard)/dashboard/transactions/$id'
    | '/(dashboard)/dashboard/transactions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authResetPasswordRoute: typeof authResetPasswordRoute
  authSigninRoute: typeof authSigninRoute
  authSignupRoute: typeof authSignupRoute
  authUnauthorizedRoute: typeof authUnauthorizedRoute
  authVerifyRoute: typeof authVerifyRoute
  landingAboutRoute: typeof landingAboutRoute
  landingContactRoute: typeof landingContactRoute
  landingFeaturesRoute: typeof landingFeaturesRoute
  landingHowItWorksRoute: typeof landingHowItWorksRoute
  landingPrivacyPolicyRoute: typeof landingPrivacyPolicyRoute
  landingSecurityRoute: typeof landingSecurityRoute
  landingTermsOfServiceRoute: typeof landingTermsOfServiceRoute
  ApiSearchRoute: typeof ApiSearchRoute
  DocsSplatRoute: typeof DocsSplatRoute
  landingIndexRoute: typeof landingIndexRoute
  DocsIndexRoute: typeof DocsIndexRoute
  dashboardAdminAuditTrailsRoute: typeof dashboardAdminAuditTrailsRoute
  dashboardAdminComplianceRoute: typeof dashboardAdminComplianceRoute
  dashboardAdminOverviewRoute: typeof dashboardAdminOverviewRoute
  dashboardAdminReportsRoute: typeof dashboardAdminReportsRoute
  dashboardAdminSettingsRoute: typeof dashboardAdminSettingsRoute
  dashboardAdminSupportRoute: typeof dashboardAdminSupportRoute
  dashboardAdminTransactionsRoute: typeof dashboardAdminTransactionsRoute
  dashboardAdminUsersRoute: typeof dashboardAdminUsersRoute
  dashboardDashboardAccountsRoute: typeof dashboardDashboardAccountsRoute
  dashboardDashboardAnalyticsRoute: typeof dashboardDashboardAnalyticsRoute
  dashboardDashboardBillsRoute: typeof dashboardDashboardBillsRoute
  dashboardDashboardCardsRoute: typeof dashboardDashboardCardsRoute
  dashboardDashboardOverviewRoute: typeof dashboardDashboardOverviewRoute
  dashboardDashboardReportsRoute: typeof dashboardDashboardReportsRoute
  dashboardDashboardRequestMoneyRoute: typeof dashboardDashboardRequestMoneyRoute
  dashboardDashboardSendMoneyRoute: typeof dashboardDashboardSendMoneyRoute
  dashboardDashboardSettingsRoute: typeof dashboardDashboardSettingsRoute
  dashboardDashboardSupportRoute: typeof dashboardDashboardSupportRoute
  dashboardDashboardTopUpRoute: typeof dashboardDashboardTopUpRoute
  dashboardMerchantAnalyticsRoute: typeof dashboardMerchantAnalyticsRoute
  dashboardMerchantApiKeysRoute: typeof dashboardMerchantApiKeysRoute
  dashboardMerchantOverviewRoute: typeof dashboardMerchantOverviewRoute
  dashboardMerchantPaymentsRoute: typeof dashboardMerchantPaymentsRoute
  dashboardMerchantSettingsRoute: typeof dashboardMerchantSettingsRoute
  dashboardMerchantSettlementsRoute: typeof dashboardMerchantSettlementsRoute
  dashboardMerchantSupportRoute: typeof dashboardMerchantSupportRoute
  dashboardMerchantWebhooksRoute: typeof dashboardMerchantWebhooksRoute
  dashboardSupportChatRoute: typeof dashboardSupportChatRoute
  dashboardSupportKnowledgeRoute: typeof dashboardSupportKnowledgeRoute
  dashboardSupportOverviewRoute: typeof dashboardSupportOverviewRoute
  dashboardSupportPaymentsRoute: typeof dashboardSupportPaymentsRoute
  dashboardSupportSettingsRoute: typeof dashboardSupportSettingsRoute
  dashboardSupportStatementsRoute: typeof dashboardSupportStatementsRoute
  dashboardSupportSupportRoute: typeof dashboardSupportSupportRoute
  dashboardSupportTicketsRoute: typeof dashboardSupportTicketsRoute
  dashboardSupportUsersRoute: typeof dashboardSupportUsersRoute
  dashboardDashboardIndexRoute: typeof dashboardDashboardIndexRoute
  dashboardDashboardTransactionsIdRoute: typeof dashboardDashboardTransactionsIdRoute
  dashboardDashboardTransactionsIndexRoute: typeof dashboardDashboardTransactionsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/docs/': {
      id: '/docs/'
      path: '/docs'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(landing)/': {
      id: '/(landing)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof landingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$': {
      id: '/docs/$'
      path: '/docs/$'
      fullPath: '/docs/$'
      preLoaderRoute: typeof DocsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/search': {
      id: '/api/search'
      path: '/api/search'
      fullPath: '/api/search'
      preLoaderRoute: typeof ApiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(landing)/terms-of-service': {
      id: '/(landing)/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/terms-of-service'
      preLoaderRoute: typeof landingTermsOfServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(landing)/security': {
      id: '/(landing)/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof landingSecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(landing)/privacy-policy': {
      id: '/(landing)/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof landingPrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(landing)/how-it-works': {
      id: '/(landing)/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof landingHowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(landing)/features': {
      id: '/(landing)/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof landingFeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(landing)/contact': {
      id: '/(landing)/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof landingContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(landing)/about': {
      id: '/(landing)/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof landingAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/verify': {
      id: '/(auth)/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof authVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/unauthorized': {
      id: '/(auth)/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof authUnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/signup': {
      id: '/(auth)/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof authSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/signin': {
      id: '/(auth)/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof authSigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/reset-password': {
      id: '/(auth)/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof authResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/dashboard/': {
      id: '/(dashboard)/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof dashboardDashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/support/users': {
      id: '/(dashboard)/support/users'
      path: '/support/users'
      fullPath: '/support/users'
      preLoaderRoute: typeof dashboardSupportUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/support/tickets': {
      id: '/(dashboard)/support/tickets'
      path: '/support/tickets'
      fullPath: '/support/tickets'
      preLoaderRoute: typeof dashboardSupportTicketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/support/support': {
      id: '/(dashboard)/support/support'
      path: '/support/support'
      fullPath: '/support/support'
      preLoaderRoute: typeof dashboardSupportSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/support/statements': {
      id: '/(dashboard)/support/statements'
      path: '/support/statements'
      fullPath: '/support/statements'
      preLoaderRoute: typeof dashboardSupportStatementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/support/settings': {
      id: '/(dashboard)/support/settings'
      path: '/support/settings'
      fullPath: '/support/settings'
      preLoaderRoute: typeof dashboardSupportSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/support/payments': {
      id: '/(dashboard)/support/payments'
      path: '/support/payments'
      fullPath: '/support/payments'
      preLoaderRoute: typeof dashboardSupportPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/support/overview': {
      id: '/(dashboard)/support/overview'
      path: '/support/overview'
      fullPath: '/support/overview'
      preLoaderRoute: typeof dashboardSupportOverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/support/knowledge': {
      id: '/(dashboard)/support/knowledge'
      path: '/support/knowledge'
      fullPath: '/support/knowledge'
      preLoaderRoute: typeof dashboardSupportKnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/support/chat': {
      id: '/(dashboard)/support/chat'
      path: '/support/chat'
      fullPath: '/support/chat'
      preLoaderRoute: typeof dashboardSupportChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/merchant/webhooks': {
      id: '/(dashboard)/merchant/webhooks'
      path: '/merchant/webhooks'
      fullPath: '/merchant/webhooks'
      preLoaderRoute: typeof dashboardMerchantWebhooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/merchant/support': {
      id: '/(dashboard)/merchant/support'
      path: '/merchant/support'
      fullPath: '/merchant/support'
      preLoaderRoute: typeof dashboardMerchantSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/merchant/settlements': {
      id: '/(dashboard)/merchant/settlements'
      path: '/merchant/settlements'
      fullPath: '/merchant/settlements'
      preLoaderRoute: typeof dashboardMerchantSettlementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/merchant/settings': {
      id: '/(dashboard)/merchant/settings'
      path: '/merchant/settings'
      fullPath: '/merchant/settings'
      preLoaderRoute: typeof dashboardMerchantSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/merchant/payments': {
      id: '/(dashboard)/merchant/payments'
      path: '/merchant/payments'
      fullPath: '/merchant/payments'
      preLoaderRoute: typeof dashboardMerchantPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/merchant/overview': {
      id: '/(dashboard)/merchant/overview'
      path: '/merchant/overview'
      fullPath: '/merchant/overview'
      preLoaderRoute: typeof dashboardMerchantOverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/merchant/api-keys': {
      id: '/(dashboard)/merchant/api-keys'
      path: '/merchant/api-keys'
      fullPath: '/merchant/api-keys'
      preLoaderRoute: typeof dashboardMerchantApiKeysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/merchant/analytics': {
      id: '/(dashboard)/merchant/analytics'
      path: '/merchant/analytics'
      fullPath: '/merchant/analytics'
      preLoaderRoute: typeof dashboardMerchantAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/dashboard/top-up': {
      id: '/(dashboard)/dashboard/top-up'
      path: '/dashboard/top-up'
      fullPath: '/dashboard/top-up'
      preLoaderRoute: typeof dashboardDashboardTopUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/dashboard/support': {
      id: '/(dashboard)/dashboard/support'
      path: '/dashboard/support'
      fullPath: '/dashboard/support'
      preLoaderRoute: typeof dashboardDashboardSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/dashboard/settings': {
      id: '/(dashboard)/dashboard/settings'
      path: '/dashboard/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof dashboardDashboardSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/dashboard/send-money': {
      id: '/(dashboard)/dashboard/send-money'
      path: '/dashboard/send-money'
      fullPath: '/dashboard/send-money'
      preLoaderRoute: typeof dashboardDashboardSendMoneyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/dashboard/request-money': {
      id: '/(dashboard)/dashboard/request-money'
      path: '/dashboard/request-money'
      fullPath: '/dashboard/request-money'
      preLoaderRoute: typeof dashboardDashboardRequestMoneyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/dashboard/reports': {
      id: '/(dashboard)/dashboard/reports'
      path: '/dashboard/reports'
      fullPath: '/dashboard/reports'
      preLoaderRoute: typeof dashboardDashboardReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/dashboard/overview': {
      id: '/(dashboard)/dashboard/overview'
      path: '/dashboard/overview'
      fullPath: '/dashboard/overview'
      preLoaderRoute: typeof dashboardDashboardOverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/dashboard/cards': {
      id: '/(dashboard)/dashboard/cards'
      path: '/dashboard/cards'
      fullPath: '/dashboard/cards'
      preLoaderRoute: typeof dashboardDashboardCardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/dashboard/bills': {
      id: '/(dashboard)/dashboard/bills'
      path: '/dashboard/bills'
      fullPath: '/dashboard/bills'
      preLoaderRoute: typeof dashboardDashboardBillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/dashboard/analytics': {
      id: '/(dashboard)/dashboard/analytics'
      path: '/dashboard/analytics'
      fullPath: '/dashboard/analytics'
      preLoaderRoute: typeof dashboardDashboardAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/dashboard/accounts': {
      id: '/(dashboard)/dashboard/accounts'
      path: '/dashboard/accounts'
      fullPath: '/dashboard/accounts'
      preLoaderRoute: typeof dashboardDashboardAccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/admin/users': {
      id: '/(dashboard)/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof dashboardAdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/admin/transactions': {
      id: '/(dashboard)/admin/transactions'
      path: '/admin/transactions'
      fullPath: '/admin/transactions'
      preLoaderRoute: typeof dashboardAdminTransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/admin/support': {
      id: '/(dashboard)/admin/support'
      path: '/admin/support'
      fullPath: '/admin/support'
      preLoaderRoute: typeof dashboardAdminSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/admin/settings': {
      id: '/(dashboard)/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof dashboardAdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/admin/reports': {
      id: '/(dashboard)/admin/reports'
      path: '/admin/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof dashboardAdminReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/admin/overview': {
      id: '/(dashboard)/admin/overview'
      path: '/admin/overview'
      fullPath: '/admin/overview'
      preLoaderRoute: typeof dashboardAdminOverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/admin/compliance': {
      id: '/(dashboard)/admin/compliance'
      path: '/admin/compliance'
      fullPath: '/admin/compliance'
      preLoaderRoute: typeof dashboardAdminComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/admin/audit-trails': {
      id: '/(dashboard)/admin/audit-trails'
      path: '/admin/audit-trails'
      fullPath: '/admin/audit-trails'
      preLoaderRoute: typeof dashboardAdminAuditTrailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/dashboard/transactions/': {
      id: '/(dashboard)/dashboard/transactions/'
      path: '/dashboard/transactions'
      fullPath: '/dashboard/transactions/'
      preLoaderRoute: typeof dashboardDashboardTransactionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/dashboard/transactions/$id': {
      id: '/(dashboard)/dashboard/transactions/$id'
      path: '/dashboard/transactions/$id'
      fullPath: '/dashboard/transactions/$id'
      preLoaderRoute: typeof dashboardDashboardTransactionsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  authForgotPasswordRoute: authForgotPasswordRoute,
  authResetPasswordRoute: authResetPasswordRoute,
  authSigninRoute: authSigninRoute,
  authSignupRoute: authSignupRoute,
  authUnauthorizedRoute: authUnauthorizedRoute,
  authVerifyRoute: authVerifyRoute,
  landingAboutRoute: landingAboutRoute,
  landingContactRoute: landingContactRoute,
  landingFeaturesRoute: landingFeaturesRoute,
  landingHowItWorksRoute: landingHowItWorksRoute,
  landingPrivacyPolicyRoute: landingPrivacyPolicyRoute,
  landingSecurityRoute: landingSecurityRoute,
  landingTermsOfServiceRoute: landingTermsOfServiceRoute,
  ApiSearchRoute: ApiSearchRoute,
  DocsSplatRoute: DocsSplatRoute,
  landingIndexRoute: landingIndexRoute,
  DocsIndexRoute: DocsIndexRoute,
  dashboardAdminAuditTrailsRoute: dashboardAdminAuditTrailsRoute,
  dashboardAdminComplianceRoute: dashboardAdminComplianceRoute,
  dashboardAdminOverviewRoute: dashboardAdminOverviewRoute,
  dashboardAdminReportsRoute: dashboardAdminReportsRoute,
  dashboardAdminSettingsRoute: dashboardAdminSettingsRoute,
  dashboardAdminSupportRoute: dashboardAdminSupportRoute,
  dashboardAdminTransactionsRoute: dashboardAdminTransactionsRoute,
  dashboardAdminUsersRoute: dashboardAdminUsersRoute,
  dashboardDashboardAccountsRoute: dashboardDashboardAccountsRoute,
  dashboardDashboardAnalyticsRoute: dashboardDashboardAnalyticsRoute,
  dashboardDashboardBillsRoute: dashboardDashboardBillsRoute,
  dashboardDashboardCardsRoute: dashboardDashboardCardsRoute,
  dashboardDashboardOverviewRoute: dashboardDashboardOverviewRoute,
  dashboardDashboardReportsRoute: dashboardDashboardReportsRoute,
  dashboardDashboardRequestMoneyRoute: dashboardDashboardRequestMoneyRoute,
  dashboardDashboardSendMoneyRoute: dashboardDashboardSendMoneyRoute,
  dashboardDashboardSettingsRoute: dashboardDashboardSettingsRoute,
  dashboardDashboardSupportRoute: dashboardDashboardSupportRoute,
  dashboardDashboardTopUpRoute: dashboardDashboardTopUpRoute,
  dashboardMerchantAnalyticsRoute: dashboardMerchantAnalyticsRoute,
  dashboardMerchantApiKeysRoute: dashboardMerchantApiKeysRoute,
  dashboardMerchantOverviewRoute: dashboardMerchantOverviewRoute,
  dashboardMerchantPaymentsRoute: dashboardMerchantPaymentsRoute,
  dashboardMerchantSettingsRoute: dashboardMerchantSettingsRoute,
  dashboardMerchantSettlementsRoute: dashboardMerchantSettlementsRoute,
  dashboardMerchantSupportRoute: dashboardMerchantSupportRoute,
  dashboardMerchantWebhooksRoute: dashboardMerchantWebhooksRoute,
  dashboardSupportChatRoute: dashboardSupportChatRoute,
  dashboardSupportKnowledgeRoute: dashboardSupportKnowledgeRoute,
  dashboardSupportOverviewRoute: dashboardSupportOverviewRoute,
  dashboardSupportPaymentsRoute: dashboardSupportPaymentsRoute,
  dashboardSupportSettingsRoute: dashboardSupportSettingsRoute,
  dashboardSupportStatementsRoute: dashboardSupportStatementsRoute,
  dashboardSupportSupportRoute: dashboardSupportSupportRoute,
  dashboardSupportTicketsRoute: dashboardSupportTicketsRoute,
  dashboardSupportUsersRoute: dashboardSupportUsersRoute,
  dashboardDashboardIndexRoute: dashboardDashboardIndexRoute,
  dashboardDashboardTransactionsIdRoute: dashboardDashboardTransactionsIdRoute,
  dashboardDashboardTransactionsIndexRoute:
    dashboardDashboardTransactionsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
